Repository eosphoros-ai/DB-GPT, pull requests merged in 2023-12, with the labels that each got.

#881 fix scene base 'of_mode' error
  pilot/scene/base.py
Labels: fix

#887 chore: update setup.py 0.4.3 version
  setup.py
Labels: internal

#892 fix: docs redirect problem fix
  docs/static/redirect.js
Labels: fix

#898 fix(conn): database conn fix special symbols
  assets/wechat.jpg
  pilot/base_modules/meta_data/meta_data.py
  pilot/connections/rdbms/base.py
  pilot/connections/rdbms/conn_clickhouse.py
  pilot/connections/rdbms/conn_duckdb.py
  pilot/connections/rdbms/conn_postgresql.py
  pilot/connections/rdbms/conn_starrocks.py
Labels: fix

#901 chore: update wechat QR code
  assets/wechat.jpg
Labels: internal

#904 fix: codestyle error fix
  pilot/scene/base_chat.py
  pilot/scene/chat_db/auto_execute/out_parser.py
Labels: fix

#906 fix: optimize api /knowledge/space/list
  pilot/server/knowledge/document_db.py
  pilot/server/knowledge/service.py
Labels: fix

#917 feat(core): Support simple DB query for sdk
  dbgpt/_private/config.py
  dbgpt/app/dbgpt_server.py
  dbgpt/app/scene/chat_db/auto_execute/chat.py
  dbgpt/core/__init__.py
  dbgpt/core/awel/task/task_impl.py
  dbgpt/core/interface/output_parser.py
  dbgpt/core/interface/retriever.py
  dbgpt/datasource/base.py
  dbgpt/datasource/db_conn_info.py
  dbgpt/datasource/manages/connection_manager.py
  dbgpt/datasource/operator/__init__.py
  dbgpt/datasource/operator/datasource_operator.py
  dbgpt/datasource/rdbms/conn_sqlite.py
  dbgpt/rag/operator/__init__.py
  dbgpt/rag/operator/datasource.py
  dbgpt/rag/summary/rdbms_db_summary.py
  examples/sdk/simple_sdk_llm_example.py
  examples/sdk/simple_sdk_llm_sql_example.py
Labels: enhancement, core

#919 fix(core): Fix fschat and alembic log conflict
  dbgpt/model/cluster/apiserver/api.py
  dbgpt/util/__init__.py
  dbgpt/util/utils.py
  pilot/meta_data/alembic.ini
  pilot/meta_data/alembic/env.py
Labels: fix, core

#931 fix: contact wechat QR code update
  assets/wechat.jpg
Labels: fix

#937 refactor: Refactor storage system
  assets/schema/knowledge_management.sql
  dbgpt/_private/config.py
  dbgpt/agent/db/my_plugin_db.py
  dbgpt/agent/db/plugin_hub_db.py
  dbgpt/agent/hub/agent_hub.py
  dbgpt/app/_cli.py
  dbgpt/app/base.py
  dbgpt/app/component_configs.py
  dbgpt/app/knowledge/chunk_db.py
  dbgpt/app/knowledge/document_db.py
  dbgpt/app/knowledge/space_db.py
  dbgpt/app/openapi/api_v1/feedback/feed_back_db.py
  dbgpt/app/prompt/prompt_manage_db.py
  dbgpt/app/scene/base_chat.py
  dbgpt/app/scene/operator/_experimental.py
  dbgpt/cli/cli_scripts.py
  dbgpt/core/__init__.py
  dbgpt/core/awel/dag/tests/test_dag.py
  dbgpt/core/interface/message.py
  dbgpt/core/interface/output_parser.py
  dbgpt/core/interface/serialization.py
  dbgpt/core/interface/storage.py
  dbgpt/core/interface/tests/__init__.py
  dbgpt/core/interface/tests/conftest.py
  dbgpt/core/interface/tests/test_message.py
  dbgpt/core/interface/tests/test_storage.py
  dbgpt/datasource/base.py
  dbgpt/datasource/manages/connect_config_db.py
  dbgpt/datasource/rdbms/base.py
  dbgpt/datasource/rdbms/conn_sqlite.py
  dbgpt/datasource/rdbms/tests/test_conn_sqlite.py
  dbgpt/model/cluster/apiserver/tests/test_api.py
  dbgpt/storage/cache/llm_cache.py
  dbgpt/storage/chat_history/chat_history_db.py
  dbgpt/storage/chat_history/storage_adapter.py
  dbgpt/storage/chat_history/store_type/duckdb_history.py
  dbgpt/storage/chat_history/store_type/meta_db_history.py
  dbgpt/storage/chat_history/tests/__init__.py
  dbgpt/storage/chat_history/tests/test_storage_adapter.py
  dbgpt/storage/metadata/__init__.py
  dbgpt/storage/metadata/_base_dao.py
  dbgpt/storage/metadata/db_manager.py
  dbgpt/storage/metadata/db_storage.py
  dbgpt/storage/metadata/meta_data.py
  dbgpt/storage/metadata/tests/__init__.py
  dbgpt/storage/metadata/tests/test_db_manager.py
  dbgpt/storage/metadata/tests/test_sqlalchemy_storage.py
  dbgpt/util/_db_migration_utils.py
  dbgpt/util/annotations.py
  dbgpt/util/pagination_utils.py
  dbgpt/util/serialization/json_serialization.py
  dbgpt/util/string_utils.py
  docs/docs/faq/install.md
  docs/docs/installation/sourcecode.md
  pilot/meta_data/alembic/env.py
Labels: internal

#941 fix(core): Fix metadata mysql url bug
  dbgpt/app/base.py
Labels: fix, core

#946 fix(core): Fix not create database bug
  dbgpt/app/base.py
  dbgpt/app/tests/__init__.py
  dbgpt/app/tests/test_base.py
Labels: fix, core

#950 feat(core): Add API authentication for serve template
  dbgpt/app/dbgpt_server.py
  dbgpt/app/initialization/db_model_initialization.py
  dbgpt/app/initialization/serve_initialization.py
  dbgpt/app/prompt/api.py
  dbgpt/app/prompt/prompt_manage_db.py
  dbgpt/app/prompt/request/request.py
  dbgpt/app/prompt/request/response.py
  dbgpt/app/prompt/service.py
  dbgpt/model/llm/__init__.py
  dbgpt/serve/core/config.py
  dbgpt/serve/core/tests/__init__.py
  dbgpt/serve/core/tests/conftest.py
  dbgpt/serve/prompt/api/endpoints.py
  dbgpt/serve/prompt/api/schemas.py
  dbgpt/serve/prompt/config.py
  dbgpt/serve/prompt/serve.py
  dbgpt/serve/prompt/service/service.py
  dbgpt/serve/prompt/tests/__init__.py
  dbgpt/serve/prompt/tests/test_endpoints.py
  dbgpt/serve/prompt/tests/test_models.py
  dbgpt/serve/prompt/tests/test_service.py
  dbgpt/serve/utils/_template_files/default_serve_template/api/endpoints.py
  dbgpt/serve/utils/_template_files/default_serve_template/api/schemas.py
  dbgpt/serve/utils/_template_files/default_serve_template/config.py
  dbgpt/serve/utils/_template_files/default_serve_template/serve.py
  dbgpt/serve/utils/_template_files/default_serve_template/service/service.py
  dbgpt/serve/utils/_template_files/default_serve_template/tests/__init__.py
  dbgpt/serve/utils/_template_files/default_serve_template/tests/test_endpoints.py
  dbgpt/serve/utils/_template_files/default_serve_template/tests/test_models.py
  dbgpt/serve/utils/_template_files/default_serve_template/tests/test_service.py
  dbgpt/serve/utils/cli.py
  dbgpt/storage/metadata/_base_dao.py
  dbgpt/storage/metadata/tests/test_base_dao.py
  dbgpt/util/config_utils.py
Labels: enhancement, core

#952 fix: if we do not set glm config, we use deault
  dbgpt/_private/config.py
Labels: fix

#954 ci: Add python unit test workflows
  .github/workflows/test-python.yml
  dbgpt/datasource/rdbms/tests/test_conn_sqlite.py
  dbgpt/model/cluster/apiserver/tests/test_api.py
  requirements/dev-requirements.txt
Labels: internal

#955 docs: add dbgpt_hub usage documents
  assets/wechat.jpg
  dbgpt/datasource/rdbms/tests/test_conn_duckdb.py
  docs/README.md
  docs/docs/application/fine_tuning_manual/dbgpt_hub.md
  docs/docs/faq/chatdata.md
  docs/docs/overview.md
  docs/sidebars.js
  docs/static/img/ft/baseline.png
  tests/intetration_tests/datasource/__init__.py
  tests/intetration_tests/datasource/test_conn_clickhouse.py
  tests/intetration_tests/datasource/test_conn_doris.py
  tests/intetration_tests/datasource/test_conn_mysql.py
  tests/intetration_tests/datasource/test_conn_starrocks.py
Labels: documentation

#959 feat(model): Support Mixtral-8x7B
  README.md
  README.zh.md
  dbgpt/app/chat_adapter.py
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/__init__.py
  dbgpt/model/adapter/base.py
  dbgpt/model/adapter/fschat_adapter.py
  dbgpt/model/adapter/hf_adapter.py
  dbgpt/model/adapter/model_adapter.py
  dbgpt/model/adapter/old_adapter.py
  dbgpt/model/adapter/template.py
  dbgpt/model/adapter/vllm_adapter.py
  dbgpt/model/cli.py
  dbgpt/model/cluster/worker/default_worker.py
  dbgpt/model/llm_utils.py
  dbgpt/model/loader.py
  dbgpt/model/model_adapter.py
Labels: enhancement, model

#960 fix(core): Move the last user's information to the end
  dbgpt/core/interface/message.py
  dbgpt/core/interface/tests/test_message.py
  dbgpt/model/proxy/llms/bard.py
  dbgpt/model/proxy/llms/chatgpt.py
Labels: fix, core

#958 fix: clickhouse connect error fix
  assets/wechat.jpg
  dbgpt/app/scene/chat_db/professional_qa/chat.py
  dbgpt/app/static/404.html
  dbgpt/app/static/404/index.html
  dbgpt/app/static/_next/static/01sV4-dnn1dUTis5H2TCy/_buildManifest.js
  dbgpt/app/static/_next/static/01sV4-dnn1dUTis5H2TCy/_ssgManifest.js
  dbgpt/app/static/_next/static/chunks/pages/_app-9bd25c3bb54ca39c.js
  dbgpt/app/static/agent/index.html
  dbgpt/app/static/chat/[scene]/[id]/index.html
  dbgpt/app/static/chat/index.html
  dbgpt/app/static/database/index.html
  dbgpt/app/static/icons/doris.png
  dbgpt/app/static/index.html
  dbgpt/app/static/knowledge/chunk/index.html
  dbgpt/app/static/knowledge/index.html
  dbgpt/app/static/models/index.html
  dbgpt/app/static/prompt/index.html
  dbgpt/datasource/base.py
  dbgpt/datasource/manages/connect_config_db.py
  dbgpt/datasource/rdbms/base.py
  dbgpt/datasource/rdbms/conn_clickhouse.py
  dbgpt/rag/summary/rdbms_db_summary.py
  setup.py
  tests/intetration_tests/datasource/test_conn_clickhouse.py
  tests/intetration_tests/datasource/test_conn_mysql.py
  web/README.md
Labels: fix

#953 feat: add gemini support
  README.zh.md
  dbgpt/_private/config.py
  dbgpt/configs/model_config.py
  dbgpt/core/interface/message.py
  dbgpt/core/interface/tests/test_message.py
  dbgpt/model/llm_out/proxy_llm.py
  dbgpt/model/proxy/llms/gemini.py
  dbgpt/model/proxy/llms/zhipu.py
Labels: enhancement

#967 feat(model): Add new LLMClient and new build tools
  Makefile
  dbgpt/core/__init__.py
  dbgpt/core/awel/operator/base.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/core/interface/llm.py
  dbgpt/datasource/rdbms/base.py
  dbgpt/datasource/rdbms/conn_clickhouse.py
  dbgpt/datasource/rdbms/conn_sqlite.py
  dbgpt/datasource/rdbms/tests/test_conn_sqlite.py
  dbgpt/model/__init__.py
  dbgpt/model/cluster/base.py
  dbgpt/model/cluster/client.py
  dbgpt/model/cluster/manager_base.py
  dbgpt/model/cluster/tests/conftest.py
  dbgpt/model/cluster/worker/default_worker.py
  dbgpt/model/cluster/worker/embedding_worker.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/model/cluster/worker/remote_manager.py
  dbgpt/model/cluster/worker/remote_worker.py
  dbgpt/model/cluster/worker_base.py
  dbgpt/model/proxy/llms/chatgpt.py
  dbgpt/model/utils/__init__.py
  dbgpt/model/utils/chatgpt_utils.py
  dbgpt/rag/summary/db_summary_client.py
  examples/awel/simple_llm_client_example.py
  examples/sdk/simple_sdk_llm_example.py
  examples/sdk/simple_sdk_llm_sql_example.py
  requirements/dev-requirements.txt
  requirements/lint-requirements.txt
  setup.py
Labels: enhancement, model

#971 fix: default proxyllm generator function
  dbgpt/model/llm_out/proxy_llm.py
Labels: fix

#972 feat(core): More AWEL operators and new prompt manager API
  assets/schema/knowledge_management.sql
  dbgpt/core/__init__.py
  dbgpt/core/awel/__init__.py
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/operator/base.py
  dbgpt/core/awel/operator/common_operator.py
  dbgpt/core/awel/runner/job_manager.py
  dbgpt/core/awel/runner/local_runner.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/core/interface/cache.py
  dbgpt/core/interface/llm.py
  dbgpt/core/interface/message.py
  dbgpt/core/interface/operator/__init__.py
  dbgpt/core/interface/operator/llm_operator.py
  dbgpt/core/interface/operator/message_operator.py
  dbgpt/core/interface/output_parser.py
  dbgpt/core/interface/prompt.py
  dbgpt/core/interface/retriever.py
  dbgpt/core/interface/serialization.py
  dbgpt/core/interface/storage.py
  dbgpt/core/interface/tests/test_message.py
  dbgpt/core/interface/tests/test_prompt.py
  dbgpt/core/interface/tests/test_storage.py
  dbgpt/core/operator/__init__.py
  dbgpt/model/__init__.py
  dbgpt/model/operator/model_operator.py
  dbgpt/model/utils/chatgpt_utils.py
  dbgpt/serve/prompt/api/endpoints.py
  dbgpt/serve/prompt/api/schemas.py
  dbgpt/serve/prompt/config.py
  dbgpt/serve/prompt/models/models.py
  dbgpt/serve/prompt/models/prompt_template_adapter.py
  dbgpt/serve/prompt/serve.py
  dbgpt/serve/prompt/service/service.py
  dbgpt/serve/prompt/tests/test_endpoints.py
  dbgpt/serve/prompt/tests/test_models.py
  dbgpt/serve/prompt/tests/test_prompt_template_adapter.py
  dbgpt/serve/prompt/tests/test_service.py
  dbgpt/storage/metadata/db_manager.py
  dbgpt/storage/metadata/db_storage.py
  dbgpt/storage/metadata/tests/test_db_manager.py
  examples/awel/simple_chat_dag_example.py
  examples/awel/simple_chat_history_example.py
  examples/awel/simple_llm_client_example.py
  examples/sdk/simple_sdk_llm_example.py
  examples/sdk/simple_sdk_llm_sql_example.py
Labels: enhancement, core

#989 fix(chat_history): chat_history_db mysql message query bug
  dbgpt/storage/chat_history/chat_history_db.py
Labels: fix

#995 chore: updata wechat qrcode
  assets/wechat.jpg
Labels: internal

#996 feat(model): Proxy model support count token
  dbgpt/model/cluster/worker/default_worker.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/model/proxy/llms/chatgpt.py
  dbgpt/model/proxy/llms/proxy_model.py
  dbgpt/model/utils/chatgpt_utils.py
  dbgpt/model/utils/token_utils.py
  dbgpt/serve/conversation/tests/test_models.py
  dbgpt/serve/prompt/tests/test_models.py
  dbgpt/serve/prompt/tests/test_service.py
  dbgpt/serve/utils/_template_files/default_serve_template/tests/test_models.py
  dbgpt/storage/chat_history/chat_history_db.py
  dbgpt/storage/metadata/_base_dao.py
  dbgpt/storage/metadata/db_manager.py
  dbgpt/storage/metadata/tests/test_base_dao.py
  dbgpt/storage/metadata/tests/test_db_manager.py
  examples/awel/simple_llm_client_example.py
Labels: enhancement, model

#1001 feat(model): Support SOLAR-10.7B-Instruct-v1.0
  README.md
  README.zh.md
  dbgpt/app/static/404.html
  dbgpt/app/static/404/index.html
  dbgpt/app/static/_next/static/DKlZHGUntVNKLp2R3uNj6/_buildManifest.js
  dbgpt/app/static/_next/static/DKlZHGUntVNKLp2R3uNj6/_ssgManifest.js
  dbgpt/app/static/_next/static/chunks/pages/_app-9bd25c3bb54ca39c.js
  dbgpt/app/static/_next/static/chunks/pages/_app-bcce90afa69c9bfa.js
  dbgpt/app/static/_next/static/fe0zdpewvAlbn-T-eLUNy/_buildManifest.js
  dbgpt/app/static/_next/static/fe0zdpewvAlbn-T-eLUNy/_ssgManifest.js
  dbgpt/app/static/agent/index.html
  dbgpt/app/static/chat/[scene]/[id]/index.html
  dbgpt/app/static/chat/index.html
  dbgpt/app/static/database/index.html
  dbgpt/app/static/index.html
  dbgpt/app/static/knowledge/chunk/index.html
  dbgpt/app/static/knowledge/index.html
  dbgpt/app/static/models/index.html
  dbgpt/app/static/models/solar_logo.png
  dbgpt/app/static/prompt/index.html
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
  scripts/build_web_static.sh
  web/public/models/solar_logo.png
  web/utils/constants.ts
Labels: enhancement, model

#1002 docs: Update README.md with Slack
  README.md
Labels: documentation
