Repository eosphoros-ai/DB-GPT, pull requests merged in 2023-10, with the labels that each got.

#643 chore:wechat expire
  assets/wechat.jpg
Labels: internal

#648 chore:wechat update
  assets/wechat.jpg
Labels: internal

#649 feat(model): llama.cpp support new GGUF file format
  .env.template
  docs/getting_started/install/llm/llama/llama_cpp.md
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/llm/llama/llama_cpp.po
  pilot/configs/model_config.py
  pilot/model/adapter.py
  pilot/model/cluster/manager_base.py
  pilot/model/cluster/worker/manager.py
  pilot/model/cluster/worker/remote_manager.py
  pilot/server/dbgpt_server.py
  setup.py
Labels: enhancement, model

#656 fix(ChatKnowledge):.env other vector db customize vector store config does not work
  .env.template
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/server/knowledge/service.py
  pilot/summary/db_summary_client.py
  pilot/vector_store/base.py
  pilot/vector_store/chroma_store.py
  pilot/vector_store/milvus_store.py
  pilot/vector_store/weaviate_store.py
Labels: fix, ChatKnowledge

#657 fix(ChatKnowledge): Chroma persist_path compatible with old version
  pilot/vector_store/chroma_store.py
Labels: fix, ChatKnowledge

#658 feat(model): Support vLLM
  .gitignore
  docker-compose.yml
  docker/base/run_sqlite.sh
  docker/base/run_sqlite_proxyllm.sh
  docker/compose_examples/cluster-docker-compose.yml
  docs/getting_started/install/docker/docker.md
  docs/getting_started/install/llm/llm.rst
  docs/getting_started/install/llm/vllm/vllm.md
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/llm/vllm/vllm.po
  pilot/configs/config.py
  pilot/configs/model_config.py
  pilot/conversation.py
  pilot/model/adapter.py
  pilot/model/base.py
  pilot/model/cli.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/conversation.py
  pilot/model/inference.py
  pilot/model/llm/llm_utils.py
  pilot/model/llm_out/guanaco_llm.py
  pilot/model/llm_out/vllm_llm.py
  pilot/model/llm_utils.py
  pilot/model/loader.py
  pilot/model/model_adapter.py
  pilot/model/parameter.py
  pilot/server/chat_adapter.py
  pilot/server/llm_manage/__init__.py
  pilot/server/llm_manage/request/__init__.py
  pilot/utils/parameter_utils.py
  pilot/utils/tests/__init__.py
  pilot/utils/tests/test_parameter_utils.py
  setup.py
Labels: enhancement, model

#661 fix:1. fix typos, 2.update CONTRIBUTING.md guideline and requirements
  CONTRIBUTING.md
  pilot/server/base.py
  pilot/summary/db_summary.py
  pilot/summary/db_summary_client.py
  pilot/summary/rdbms_db_summary.py
  requirements/dev-requirements.txt
Labels: fix

#665 feat(core): Support cross-service data recording and analyze
  docker/base/build_image.sh
  docs/getting_started/observability.md
  docs/index.rst
  docs/locales/zh_CN/LC_MESSAGES/getting_started/observability.po
  pilot/component.py
  pilot/model/adapter.py
  pilot/model/base.py
  pilot/model/cluster/base.py
  pilot/model/cluster/embedding/loader.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/model_adapter.py
  pilot/openapi/api_v1/api_v1.py
  pilot/scene/base_chat.py
  pilot/scripts/cli_scripts.py
  pilot/server/component_configs.py
  pilot/server/dbgpt_server.py
  pilot/server/llmserver.py
  pilot/utils/parameter_utils.py
  pilot/utils/tracer/__init__.py
  pilot/utils/tracer/base.py
  pilot/utils/tracer/span_storage.py
  pilot/utils/tracer/tests/__init__.py
  pilot/utils/tracer/tests/test_base.py
  pilot/utils/tracer/tests/test_span_storage.py
  pilot/utils/tracer/tests/test_tracer_impl.py
  pilot/utils/tracer/tracer_cli.py
  pilot/utils/tracer/tracer_impl.py
  pilot/utils/tracer/tracer_middleware.py
Labels: enhancement, core

#666 docs(core): Fix zh_CN document error for Debugging
  docs/locales/zh_CN/LC_MESSAGES/getting_started/observability.po
Labels: documentation, fix, core

#619 fix: use openai package instead of requests
  pilot/model/proxy/llms/chatgpt.py
Labels: fix

#667 docs: fix small typo
  README.md
Labels: documentation

#668 fix(model): Fix openai adapt previous proxy_server_url configuration and support azure openai model
  pilot/model/parameter.py
  pilot/model/proxy/llms/chatgpt.py
Labels: fix, model

#670 feat(core): Read and save system information to tracer
  .dockerignore
  docker/base/Dockerfile
  pilot/model/cluster/embedding/loader.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/server/dbgpt_server.py
  pilot/utils/system_utils.py
  pilot/utils/tracer/tracer_cli.py
Labels: enhancement, core

#673 chore: wechat code update
  assets/wechat.jpg
Labels: internal

#674 fix(model): Fix load some quantization model error
  pilot/model/model_adapter.py
  pilot/utils/tracer/span_storage.py
  pilot/utils/tracer/tests/test_base.py
  pilot/utils/tracer/tests/test_span_storage.py
Labels: fix, model

#675 fix(ChatData): db schema not complete bug
  pilot/summary/db_summary_client.py
Labels: fix, ChatData

#690 feat(core): Support use custom log file name and tracer file name
  pilot/model/cluster/controller/controller.py
  pilot/model/cluster/worker/manager.py
  pilot/model/parameter.py
  pilot/server/base.py
  pilot/server/dbgpt_server.py
  pilot/utils/tracer/span_storage.py
  pilot/utils/tracer/tests/test_span_storage.py
Labels: enhancement, core

#693 feat:switch BaseDao from meta_data
  pilot/openapi/api_v1/feedback/feed_back_db.py
  pilot/server/knowledge/chunk_db.py
  pilot/server/knowledge/document_db.py
  pilot/server/knowledge/space_db.py
  pilot/server/prompt/prompt_manage_db.py
Labels: enhancement

#696 feat(ChatExcel): ChatExcel example file
  docker/examples/excel/example.xlsx
  docker/examples/excel/zx.csv
Labels: enhancement, ChatExcel

#699 feat(ChatExcel): ChatExcel example file
  docs/getting_started/application/chatagent/chatagent.md
  pilot/scene/chat_agent/chat.py
  pilot/scene/chat_data/chat_excel/excel_analyze/chat.py
Labels: enhancement, ChatExcel

#708 fix(model): Fix remote embedding model start error
  pilot/model/cluster/manager_base.py
  setup.py
Labels: fix, model

#717 docs:add RAG in action arch image
  README.md
  README.zh.md
  assets/DB-GPT.png
  assets/DB-GPT_zh.png
  assets/RAG-IN-ACTION.jpg
Labels: documentation

#722 feat(core): Enhance server request processing performance
  pilot/base_modules/agent/commands/disply_type/show_chart_gen.py
  pilot/base_modules/agent/hub/agent_hub.py
  pilot/base_modules/agent/plugins_util.py
  pilot/base_modules/meta_data/meta_data.py
  pilot/logs.py
  pilot/memory/chat_history/chat_hisotry_factory.py
  pilot/memory/chat_history/store_type/meta_db_history.py
  pilot/openapi/api_v1/api_v1.py
  pilot/scene/base_chat.py
  pilot/scene/chat_agent/chat.py
  pilot/scene/chat_agent/out_parser.py
  pilot/scene/chat_dashboard/chat.py
  pilot/scene/chat_data/chat_excel/excel_analyze/chat.py
  pilot/scene/chat_data/chat_excel/excel_learning/chat.py
  pilot/scene/chat_db/auto_execute/chat.py
  pilot/scene/chat_db/professional_qa/chat.py
  pilot/scene/chat_execution/chat.py
  pilot/scene/chat_factory.py
  pilot/scene/chat_knowledge/inner_db_summary/chat.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/scene/chat_normal/chat.py
  pilot/server/componet_configs.py
  pilot/utils/executor_utils.py
  scripts/setup_autodl_env.sh
  setup.py
Labels: enhancement, core

#725 chore:wechat expire
  assets/wechat.jpg
Labels: internal

#734 fix(model): Fix some model missing stop tokens bug
  pilot/model/model_adapter.py
  pilot/scene/chat_factory.py
Labels: fix, model

#740 docs: add prompt management
  docs/locales/zh_CN/LC_MESSAGES/modules/prompts.po
  docs/modules/prompts.md
Labels: documentation

#741 feat(core): Support configuration metadata database name in .env file
  .env.template
  assets/schema/history.sql
  assets/schema/knowledge_management.sql
  assets/schema/prompt_management.sql
  docs/getting_started/faq/deploy/deploy_faq.md
  docs/getting_started/faq/kbqa/kbqa_faq.md
  docs/locales/zh_CN/LC_MESSAGES/getting_started/faq/deploy/deploy_faq.po
  docs/locales/zh_CN/LC_MESSAGES/getting_started/faq/kbqa/kbqa_faq.po
  pilot/base_modules/agent/db/my_plugin_db.py
  pilot/base_modules/agent/db/plugin_hub_db.py
  pilot/base_modules/meta_data/meta_data.py
  pilot/base_modules/meta_data/requirement.txt
  pilot/configs/config.py
  pilot/connections/manages/connect_config_db.py
  pilot/memory/chat_history/chat_history_db.py
  pilot/memory/chat_history/store_type/meta_db_history.py
  pilot/model/parameter.py
  pilot/openapi/api_v1/feedback/feed_back_db.py
  pilot/server/base.py
  pilot/server/knowledge/chunk_db.py
  pilot/server/knowledge/document_db.py
  pilot/server/knowledge/space_db.py
  pilot/server/prompt/prompt_manage_db.py
  requirements/dev-requirements.txt
Labels: enhancement, core

#746 docs: Update README.md
  README.md
Labels: documentation

#747 feat(model): Support AquilaChat2-34B
  .env.template
  docs/getting_started/faq/llm/llm_faq.md
  docs/locales/zh_CN/LC_MESSAGES/getting_started/faq/llm/llm_faq.po
  pilot/configs/config.py
  pilot/model/cluster/controller/controller.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/embedding_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/loader.py
  pilot/model/model_adapter.py
  pilot/model/proxy/llms/chatgpt.py
  pilot/server/dbgpt_server.py
  pilot/utils/parameter_utils.py
  pilot/utils/utils.py
Labels: enhancement, model

#750 chore:discord expire
  README.md
  README.zh.md
Labels: internal

#749 docs: corrected all grammatical errors in README.md
  README.md
Labels: documentation

#751 fix typo
  docs/getting_started/install/environment/environment.md
Labels: fix

#760 feat(model) Support the DB-GPT-Hub trained mode
  pilot/configs/model_config.py
  pilot/model/adapter.py
  pilot/model/conversation.py
  pilot/model/model_adapter.py
  pilot/server/chat_adapter.py
Labels: enhancement, model

#761 fixed typos
  README.md
Labels: fix

#762 docs: fix README typos
  README.md
Labels: documentation, fix
