Repository eosphoros-ai/DB-GPT, pull requests merged in 2023-09, with the labels that each got.

#560 chore: modify wechat image
  assets/wechat.jpg
Labels: internal

#566 feat(model): Unified Deployment Mode with multi-model and add command line chat with model
  pilot/model/cli.py
  pilot/model/controller/controller.py
  pilot/model/controller/registry.py
  pilot/model/parameter.py
  pilot/model/worker/default_worker.py
  pilot/model/worker/manager.py
  pilot/scripts/cli_scripts.py
  pilot/server/_cli.py
  pilot/server/dbgpt_server.py
  pilot/utils/command_utils.py
Labels: enhancement, model

#568 fix(model): fix proxy llm with fix model from CONFIG
  pilot/model/llm_out/proxy_llm.py
Labels: fix, model

#570 feat(model): supports the deployment of multiple models through the API and add the corresponding command line interface
  pilot/configs/model_config.py
  pilot/model/adapter.py
  pilot/model/base.py
  pilot/model/cli.py
  pilot/model/cluster/__init__.py
  pilot/model/cluster/base.py
  pilot/model/cluster/controller/__init__.py
  pilot/model/cluster/controller/controller.py
  pilot/model/cluster/controller/ray_controller.py
  pilot/model/cluster/controller/tests/__init__.py
  pilot/model/cluster/controller/tests/test_registry.py
  pilot/model/cluster/controller_base.py
  pilot/model/cluster/manager_base.py
  pilot/model/cluster/registry.py
  pilot/model/cluster/worker/__init__.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/embedding_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/cluster/worker/ray_worker.py
  pilot/model/cluster/worker/remote_manager.py
  pilot/model/cluster/worker/remote_worker.py
  pilot/model/cluster/worker_base.py
  pilot/model/llm_utils.py
  pilot/model/loader.py
  pilot/model/parameter.py
  pilot/scene/base_chat.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/server/dbgpt_server.py
  pilot/server/knowledge/api.py
  pilot/server/knowledge/service.py
  pilot/server/llmserver.py
  pilot/summary/db_summary_client.py
  pilot/utils/command_utils.py
  pilot/utils/module_utils.py
  pilot/utils/parameter_utils.py
  pilot/vector_store/extract_tovec.py
  pilot/vector_store/file_loader.py
  requirements.txt
Labels: enhancement, model

#574 feat(model): multi-model supports embedding model and simple component design implementation
  docker/compose_examples/cluster-docker-compose.yml
  docs/_static/img/muti-model-cluster-overview.png
  docs/getting_started/install.rst
  docs/getting_started/install/cluster/cluster.rst
  docs/getting_started/install/cluster/kubernetes/index.md
  docs/getting_started/install/cluster/vms/index.md
  docs/getting_started/install/llm/llm.rst
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install.po
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/cluster/cluster.po
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/cluster/kubernetes/index.po
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/cluster/vms/index.po
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/llm/llm.po
  docs/requirements.txt
  pilot/componet.py
  pilot/configs/config.py
  pilot/connections/manages/connection_manager.py
  pilot/connections/rdbms/tests/mange_t.py
  pilot/embedding_engine/embedding_engine.py
  pilot/embedding_engine/embedding_factory.py
  pilot/model/adapter.py
  pilot/model/cli.py
  pilot/model/cluster/__init__.py
  pilot/model/cluster/controller/controller.py
  pilot/model/cluster/embedding/__init__.py
  pilot/model/cluster/embedding/remote_embedding.py
  pilot/model/cluster/manager_base.py
  pilot/model/cluster/registry.py
  pilot/model/cluster/worker/embedding_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/cluster/worker/remote_manager.py
  pilot/model/cluster/worker/remote_worker.py
  pilot/model/parameter.py
  pilot/openapi/api_v1/api_v1.py
  pilot/scene/chat_dashboard/chat.py
  pilot/scene/chat_db/auto_execute/chat.py
  pilot/scene/chat_db/professional_qa/chat.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/server/base.py
  pilot/server/componet_configs.py
  pilot/server/dbgpt_server.py
  pilot/server/knowledge/api.py
  pilot/server/knowledge/service.py
  pilot/server/llmserver.py
  pilot/summary/db_summary_client.py
  pilot/utils/api_utils.py
  pilot/vector_store/extract_tovec.py
  pilot/vector_store/file_loader.py
Labels: enhancement, model

#583 feat(model): support InternLM
  assets/wechat.jpg
  pilot/componet.py
  pilot/configs/model_config.py
  pilot/model/adapter.py
  pilot/model/cluster/controller/controller.py
  pilot/model/conversation.py
  pilot/openapi/api_v1/api_v1.py
  pilot/server/chat_adapter.py
  pilot/server/componet_configs.py
Labels: enhancement, model

#587 fix(model): Fix remote embedding model error in some case
  pilot/componet.py
  pilot/embedding_engine/embedding_factory.py
  pilot/model/cluster/worker/embedding_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/server/base.py
  pilot/server/componet_configs.py
  pilot/server/dbgpt_server.py
Labels: fix, model

#589 chore:wechat group
  assets/wechat.jpg
Labels: internal

#590 chore:wechat group
  assets/wechat.jpg
Labels: internal

#592 chore: readme format display problem fix
  README.md
  README.zh.md
Labels: internal

#591 feat(model): support openai embedding model
  .env.template
  README.md
  README.zh.md
  docker/compose_examples/cluster-docker-compose.yml
  docs/getting_started/install/llm/llm.rst
  pilot/componet.py
  pilot/configs/config.py
  pilot/configs/model_config.py
  pilot/embedding_engine/embedding_factory.py
  pilot/model/adapter.py
  pilot/model/cluster/embedding/loader.py
  pilot/model/cluster/worker/embedding_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/cluster/worker/remote_worker.py
  pilot/model/parameter.py
  pilot/server/componet_configs.py
  requirements.txt
  scripts/setup_autodl_env.sh
  setup.py
Labels: enhancement, model

#595 chore: latest AutoDL image
  README.md
  README.zh.md
  pilot/embedding_engine/loader/ppt_loader.py
  scripts/setup_autodl_env.sh
Labels: internal

#599 feat(prompt): prompt manage support
  assets/schema/prompt_management.sql
  pilot/server/dbgpt_server.py
  pilot/server/prompt/__init__.py
  pilot/server/prompt/api.py
  pilot/server/prompt/prompt_manage_db.py
  pilot/server/prompt/request/__init__.py
  pilot/server/prompt/request/request.py
  pilot/server/prompt/request/response.py
  pilot/server/prompt/service.py
Labels: enhancement, prompt

#600 feat(model): new worker manager factory componet
  pilot/component.py
  pilot/configs/config.py
  pilot/connections/manages/connection_manager.py
  pilot/embedding_engine/embedding_factory.py
  pilot/model/base.py
  pilot/model/cluster/__init__.py
  pilot/model/cluster/controller/controller.py
  pilot/model/cluster/manager_base.py
  pilot/model/cluster/worker/manager.py
  pilot/model/llm_utils.py
  pilot/openapi/api_v1/api_v1.py
  pilot/scene/base_chat.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/server/base.py
  pilot/server/component_configs.py
  pilot/server/dbgpt_server.py
  pilot/server/knowledge/api.py
  pilot/server/knowledge/service.py
  pilot/summary/db_summary_client.py
  pilot/utils/parameter_utils.py
Labels: enhancement, model

#606 feat(core): Multi-module dependency splitting
  .github/release-drafter.yml
  .gitignore
  README.md
  README.zh.md
  docker/base/Dockerfile
  docker/base/build_image.sh
  docs/getting_started/install/cluster/vms/index.md
  docs/getting_started/install/deploy/deploy.md
  docs/getting_started/install/llm/llm.rst
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/cluster/vms/index.po
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/llm/llm.po
  pilot/common/plugins.py
  pilot/configs/config.py
  pilot/configs/model_config.py
  pilot/embedding_engine/embedding_engine.py
  pilot/embedding_engine/markdown_embedding.py
  pilot/embedding_engine/source_embedding.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/proxy/llms/bard.py
  pilot/scene/chat_data/chat_excel/excel_learning/chat.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/server/knowledge/_cli/knowledge_cli.py
  pilot/server/static/_next/static/chunks/79.e75d7ee2dd885405.js
  pilot/server/static/_next/static/chunks/pages/index-d5aba6bbbc1d8aaa.js
  pilot/summary/db_summary_client.py
  pilot/vector_store/chroma_store.py
  requirements.txt
  requirements/dev-requirements.txt
  setup.py
Labels: enhancement, core

#609 feat(ChatKnowledge): return topk document source (KBQA)
  assets/schema/history.sql
  pilot/configs/config.py
  pilot/openapi/api_v1/api_v1.py
  pilot/openapi/api_v1/feedback/__init__.py
  pilot/openapi/api_v1/feedback/api_fb_v1.py
  pilot/openapi/api_v1/feedback/feed_back_db.py
  pilot/openapi/api_v1/feedback/feed_back_model.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/server/dbgpt_server.py
Labels: enhancement, ChatKnowledge

#611 feat(web): Add incremental response to streaming response for `/v1/chat/completion` request
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/embedding_worker.py
  pilot/model/loader.py
  pilot/openapi/api_v1/api_v1.py
  pilot/openapi/api_view_model.py
  pilot/utils/model_utils.py
Labels: enhancement, web

#616 fix: proxyllm do not need controller_addr
  pilot/model/cluster/worker/manager.py
  pilot/model/parameter.py
Labels: fix

#623 fix:doc build error
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/conf.py
Labels: fix

#624 chore:wechat expire
  assets/wechat.jpg
Labels: internal

#628 fix(core): Use thread pool to replace native threading.Thread
  pilot/component.py
  pilot/configs/config.py
  pilot/connections/manages/connection_manager.py
  pilot/server/component_configs.py
  pilot/server/knowledge/_cli/knowledge_client.py
  pilot/server/knowledge/service.py
  pilot/utils/executor_utils.py
  setup.py
Labels: fix, core

#633 fix(ChatData):pyspark lazy load
  pilot/connections/conn_spark.py
  setup.py
Labels: fix, ChatData

#636 feat(ChatKnowledge): Add custom text separators and refactor log configuration
  .env.template
  docs/getting_started/application/kbqa/kbqa.md
  docs/locales/zh_CN/LC_MESSAGES/getting_started/application/kbqa/kbqa.po
  pilot/agent/json_fix_llm.py
  pilot/commands/built_in/image_gen.py
  pilot/commands/disply_type/show_chart_gen.py
  pilot/commands/disply_type/show_table_gen.py
  pilot/commands/disply_type/show_text_gen.py
  pilot/common/plugins.py
  pilot/configs/config.py
  pilot/configs/model_config.py
  pilot/connections/rdbms/base_dao.py
  pilot/embedding_engine/__init__.py
  pilot/embedding_engine/pre_text_splitter.py
  pilot/json_utils/json_fix_general.py
  pilot/json_utils/utilities.py
  pilot/model/adapter.py
  pilot/model/cluster/controller/controller.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/llm/llama_cpp/llama_cpp.py
  pilot/model/loader.py
  pilot/model/parameter.py
  pilot/openapi/api_v1/api_v1.py
  pilot/openapi/api_v1/editor/api_editor_v1.py
  pilot/out_parser/base.py
  pilot/scene/base_chat.py
  pilot/scene/chat_dashboard/data_loader.py
  pilot/scene/chat_dashboard/out_parser.py
  pilot/scene/chat_data/chat_excel/excel_analyze/out_parser.py
  pilot/scene/chat_data/chat_excel/excel_learning/out_parser.py
  pilot/scene/chat_db/auto_execute/out_parser.py
  pilot/scene/chat_db/professional_qa/out_parser.py
  pilot/scene/chat_execution/out_parser.py
  pilot/scene/chat_knowledge/inner_db_summary/out_parser.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/scene/chat_knowledge/v1/out_parser.py
  pilot/scene/chat_normal/out_parser.py
  pilot/server/base.py
  pilot/server/dbgpt_server.py
  pilot/server/knowledge/_cli/knowledge_cli.py
  pilot/server/knowledge/_cli/knowledge_client.py
  pilot/server/knowledge/api.py
  pilot/server/knowledge/request/request.py
  pilot/server/knowledge/service.py
  pilot/speech/eleven_labs.py
  pilot/summary/db_summary_client.py
  pilot/utils/__init__.py
  pilot/utils/api_utils.py
  pilot/utils/utils.py
  pilot/vector_store/chroma_store.py
  pilot/vector_store/milvus_store.py
  pilot/vector_store/weaviate_store.py
  setup.py
Labels: enhancement, ChatKnowledge

#626 feat: add postgresql support
  pilot/connections/manages/connection_manager.py
  pilot/connections/rdbms/conn_postgresql.py
  pilot/scene/chat_dashboard/out_parser.py
  pilot/scene/chat_dashboard/prompt.py
  setup.py
Labels: enhancement

#637 chore: Roll back json parsing code
  pilot/scene/chat_dashboard/out_parser.py
Labels: internal

#639 feat(ci): modify PR release drafter
  .github/release-drafter.yml
Labels: enhancement

#641 docs:0.3.9 version
  docs/conf.py
  setup.py
Labels: documentation

#642 chore:discord expire
  README.md
  README.zh.md
Labels: internal
