Repository eosphoros-ai/DB-GPT, pull requests merged in 2023-11, with the labels that each got.

#765 chores: update wechat
  assets/wechat.jpg
Labels: internal

#768 feat(model): Support OpenAI-Compatible RESTful APIs
  docker/compose_examples/cluster-docker-compose.yml
  docs/getting_started/install/cluster/cluster.rst
  docs/getting_started/install/cluster/openai.md
  docs/getting_started/install/llm/proxyllm/proxyllm.md
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/cluster/openai.po
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/environment/environment.po
  docs/locales/zh_CN/LC_MESSAGES/modules/knowledge.po
  pilot/base_modules/agent/db/__init__.py
  pilot/component.py
  pilot/model/base.py
  pilot/model/cli.py
  pilot/model/cluster/__init__.py
  pilot/model/cluster/apiserver/__init__.py
  pilot/model/cluster/apiserver/api.py
  pilot/model/cluster/apiserver/tests/__init__.py
  pilot/model/cluster/apiserver/tests/test_api.py
  pilot/model/cluster/controller/controller.py
  pilot/model/cluster/registry.py
  pilot/model/cluster/tests/__init__.py
  pilot/model/cluster/tests/conftest.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/cluster/worker/tests/test_manager.py
  pilot/model/model_adapter.py
  pilot/model/parameter.py
  pilot/scene/base_message.py
  pilot/utils/openai_utils.py
  requirements/dev-requirements.txt
Labels: enhancement, model

#775 feat(core): More trace records for DB-GPT
  assets/schema/knowledge_management.sql
  pilot/scene/base_chat.py
  pilot/scene/chat_agent/chat.py
  pilot/scene/chat_dashboard/chat.py
  pilot/scene/chat_data/chat_excel/excel_analyze/chat.py
  pilot/scene/chat_data/chat_excel/excel_learning/chat.py
  pilot/scene/chat_db/auto_execute/chat.py
  pilot/scene/chat_db/auto_execute/out_parser.py
  pilot/scene/chat_db/professional_qa/chat.py
  pilot/scene/chat_execution/chat.py
  pilot/scene/chat_knowledge/inner_db_summary/chat.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/scene/chat_normal/chat.py
  pilot/utils/executor_utils.py
  pilot/utils/tracer/__init__.py
  pilot/utils/tracer/tracer_cli.py
  pilot/utils/tracer/tracer_impl.py
Labels: enhancement, core

#782 feat(core): Support custom trace storage
  docker/base/Dockerfile
  docs/getting_started/install/deploy.rst
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/deploy.po
  docs/locales/zh_CN/LC_MESSAGES/index.po
  pilot/model/cluster/worker/manager.py
  pilot/model/parameter.py
  pilot/model/proxy/llms/tongyi.py
  pilot/server/base.py
  pilot/server/dbgpt_server.py
  pilot/utils/tracer/__init__.py
  pilot/utils/tracer/base.py
  pilot/utils/tracer/span_storage.py
  pilot/utils/tracer/tests/test_span_storage.py
  pilot/utils/tracer/tracer_impl.py
Labels: enhancement, core

#795 docs: update overview
  README.md
  README.zh.md
  docs/index.rst
  docs/locales/zh_CN/LC_MESSAGES/getting_started/install/environment/environment.po
  docs/locales/zh_CN/LC_MESSAGES/index.po
  docs/reference.md
Labels: documentation

#804 fix(Model): Compatible with openai 1.x.x, compatible with AzureOpeai
  pilot/model/proxy/llms/chatgpt.py
Labels: fix

#805 fix: compile OpenAI 1.x.x version
  pilot/model/proxy/llms/chatgpt.py
Labels: fix

#803 feat(model): Support model cache and new Agentic Workflow Expression Language(AWEL)
  .env.template
  pilot/awel/__init__.py
  pilot/awel/dag/__init__.py
  pilot/awel/dag/base.py
  pilot/awel/dag/tests/__init__.py
  pilot/awel/dag/tests/test_dag.py
  pilot/awel/operator/__init__.py
  pilot/awel/operator/base.py
  pilot/awel/operator/common_operator.py
  pilot/awel/operator/stream_operator.py
  pilot/awel/resource/__init__.py
  pilot/awel/resource/base.py
  pilot/awel/runner/__init__.py
  pilot/awel/runner/job_manager.py
  pilot/awel/runner/local_runner.py
  pilot/awel/task/__init__.py
  pilot/awel/task/base.py
  pilot/awel/task/task_impl.py
  pilot/awel/tests/__init__.py
  pilot/awel/tests/conftest.py
  pilot/awel/tests/test_http_operator.py
  pilot/awel/tests/test_run_dag.py
  pilot/cache/__init__.py
  pilot/cache/base.py
  pilot/cache/embedding_cache.py
  pilot/cache/llm_cache.py
  pilot/cache/manager.py
  pilot/cache/protocal/__init__.py
  pilot/cache/protocal/json_protocal.py
  pilot/cache/storage/__init__.py
  pilot/cache/storage/base.py
  pilot/cache/storage/disk/__init__.py
  pilot/cache/storage/disk/disk_storage.py
  pilot/cache/storage/tests/__init__.py
  pilot/cache/storage/tests/test_storage.py
  pilot/component.py
  pilot/configs/config.py
  pilot/configs/model_config.py
  pilot/model/cluster/base.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/cluster/worker/remote_manager.py
  pilot/model/model_adapter.py
  pilot/model/operator/__init__.py
  pilot/model/operator/model_operator.py
  pilot/scene/base_chat.py
  pilot/server/component_configs.py
  pilot/utils/memory_utils.py
  setup.py
Labels: enhancement, model

#808 feat(model): Add LLM benchmarks code
  docker/examples/benchmarks/benchmarks_llm_11k_prompt.txt
  pilot/configs/model_config.py
  pilot/model/base.py
  pilot/model/cluster/base.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/cluster/worker/manager.py
  pilot/model/llm_out/vllm_llm.py
  pilot/model/model_adapter.py
  pilot/scene/base_chat.py
  pilot/utils/benchmarks/__init__.py
  pilot/utils/benchmarks/llm/__init__.py
  pilot/utils/benchmarks/llm/fastchat_benchmarks_inference.py
  pilot/utils/benchmarks/llm/llm_benchmarks.py
  scripts/run_llm_benchmarks.sh
Labels: enhancement, model

#813 fix(ChatKnowledge):Milvus create collection bug
  pilot/vector_store/milvus_store.py
Labels: fix, ChatKnowledge

#815 feat(awel): AWEL supports http trigger and add some AWEL examples
  examples/awel/simple_chat_dag_example.py
  examples/awel/simple_dag_example.py
  examples/awel/simple_rag_example.py
  pilot/awel/__init__.py
  pilot/awel/base.py
  pilot/awel/dag/base.py
  pilot/awel/dag/dag_manager.py
  pilot/awel/dag/loader.py
  pilot/awel/operator/base.py
  pilot/awel/operator/common_operator.py
  pilot/awel/runner/local_runner.py
  pilot/awel/trigger/__init__.py
  pilot/awel/trigger/base.py
  pilot/awel/trigger/http_trigger.py
  pilot/awel/trigger/trigger_manager.py
  pilot/component.py
  pilot/configs/model_config.py
  pilot/memory/chat_history/store_type/meta_db_history.py
  pilot/model/operator/model_operator.py
  pilot/model/proxy/llms/chatgpt.py
  pilot/scene/base_chat.py
  pilot/scene/base_message.py
  pilot/scene/chat_data/chat_excel/excel_reader.py
  pilot/scene/chat_db/auto_execute/out_parser.py
  pilot/scene/chat_knowledge/extract_entity/chat.py
  pilot/scene/chat_knowledge/extract_triplet/chat.py
  pilot/scene/chat_knowledge/refine_summary/chat.py
  pilot/scene/chat_knowledge/summary/chat.py
  pilot/scene/chat_knowledge/v1/chat.py
  pilot/scene/operator/__init__.py
  pilot/scene/operator/_experimental.py
  pilot/server/component_configs.py
  pilot/utils/parameter_utils.py
Labels: enhancement

#817 feat(awel): Modify AWEL http trigger route function
  examples/awel/simple_chat_dag_example.py
  examples/awel/simple_dag_example.py
  examples/awel/simple_rag_example.py
  pilot/awel/trigger/base.py
  pilot/awel/trigger/http_trigger.py
  setup.py
Labels: enhancement

#818 feat(usage): add tests cases for dashboard
  docker/examples/dashboard/test_case_mysql_data.py
Labels: enhancement

#823 feat(model): Add more support model list and modify LLM benchmarks
  README.md
  README.zh.md
  pilot/configs/model_config.py
  pilot/model/base.py
  pilot/model/cluster/worker/default_worker.py
  pilot/utils/benchmarks/llm/fastchat_benchmarks_inference.py
  pilot/utils/benchmarks/llm/llm_benchmarks.py
  pilot/utils/model_utils.py
  scripts/run_llm_benchmarks.sh
Labels: enhancement, model

#824 chores: update contact QR code
  assets/wechat.jpg
Labels: internal

#837 feat(model): Support Yi-34B-Chat
  README.md
  README.zh.md
  pilot/configs/model_config.py
  pilot/model/cluster/worker/default_worker.py
  pilot/model/llm_out/hf_chat_llm.py
  pilot/model/model_adapter.py
  pilot/scene/base_message.py
  setup.py
Labels: enhancement, model

#854 feat(core): MTB supports multi-user and multi-system fields
  assets/schema/knowledge_management.sql
  pilot/base_modules/agent/db/my_plugin_db.py
  pilot/configs/model_config.py
  pilot/connections/manages/connect_config_db.py
  pilot/memory/chat_history/base.py
  pilot/memory/chat_history/chat_hisotry_factory.py
  pilot/memory/chat_history/chat_history_db.py
  pilot/memory/chat_history/store_type/duckdb_history.py
  pilot/memory/chat_history/store_type/meta_db_history.py
  pilot/openapi/api_v1/api_v1.py
  pilot/openapi/api_view_model.py
  pilot/scene/base_chat.py
  pilot/scene/message.py
  pilot/server/prompt/prompt_manage_db.py
  setup.py
Labels: enhancement, core

#856 docs: redirect documents to newdocs
  README.md
Labels: documentation

#820 bugfix(Azure): fix index out of range error due to Azure Openai reponses an empty chunk at first
  pilot/model/proxy/llms/chatgpt.py
Labels: fix, model

#866 fix(core): Fix api error when upload files
  pilot/conversation.py
  pilot/language/lang_content_mapping.py
  pilot/language/translation_handler.py
  pilot/log/__init__.py
  pilot/log/json_handler.py
  pilot/logs.py
  pilot/openapi/api_v1/api_v1.py
  pilot/openapi/api_view_model.py
  setup.py
Labels: fix, core

#869 chores: remove extra unuse code and update contact info
  README.md
  README.zh.md
  assets/wechat.jpg
  pilot/model/cache/__init__.py
  pilot/model/cache/base.py
  pilot/model/cache/disk_cache.py
  pilot/model/cache/gpt_cache.py
  pilot/model/cache/memory_cache.py
Labels: internal

#871 fix(llmproxy): fix openai chatgpt api response error
  pilot/model/proxy/llms/chatgpt.py
Labels: fix
