Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-01, with the labels that each got.

#999 fix(clickhouse): fix information_schema
  dbgpt/datasource/rdbms/conn_clickhouse.py
Labels: fix, cli

#1006 docs: add paper link and citation
  README.md
  README.zh.md
Labels: documentation

#1009 feat(model): Support Baichuan API
  README.zh.md
  dbgpt/_private/config.py
  dbgpt/model/proxy/llms/baichuan.py
  docs/docs/modules/smmf.md
Labels: enhancement, model

#1010 chore: Fix baichuan API pylint error
  dbgpt/_private/config.py
  dbgpt/model/proxy/llms/baichuan.py
Labels: internal

#1011 build: Improve build performance
  Makefile
Labels: build

#1013 docs: update author info
  README.md
  README.zh.md
Labels: documentation

#1022 feat(build):Add Template for Pull Request
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#1028 feat(model): Fix chatgpt message format bug
  dbgpt/model/proxy/llms/chatgpt.py
Labels: enhancement, model

#1027 fix(ChatKnowledge): delete Chroma by vector ids did not success
  dbgpt/storage/vector_store/chroma_store.py
Labels: fix, ChatKnowledge

#1033 fix(model): Fix device MPS load llama error
  dbgpt/model/llm/monkey_patch.py
  dbgpt/model/loader.py
Labels: fix, model

#1035 docs: update chat_knowledge.md and wechat.jpg
  assets/wechat.jpg
  docs/docs/application/started_tutorial/chat_knowledge.md
  setup.py
Labels: documentation

#1023 feat(multi-agents):Add Summary Assistant Agent According to User's Question
  dbgpt/agent/agents/expand/summary_assistant_agent.py
  examples/agents/single_summary_agent_dialogue_example.py
Labels: enhancement, agent

#1039 feat(awel): New MessageConverter and more AWEL operators
  .gitignore
  Makefile
  dbgpt/app/scene/base_chat.py
  dbgpt/core/__init__.py
  dbgpt/core/awel/__init__.py
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/operator/base.py
  dbgpt/core/awel/runner/local_runner.py
  dbgpt/core/interface/llm.py
  dbgpt/core/interface/message.py
  dbgpt/core/interface/operator/composer_operator.py
  dbgpt/core/interface/operator/llm_operator.py
  dbgpt/core/interface/operator/message_operator.py
  dbgpt/core/interface/operator/prompt_operator.py
  dbgpt/core/interface/prompt.py
  dbgpt/core/interface/tests/test_message.py
  dbgpt/core/interface/tests/test_prompt.py
  dbgpt/core/operator/__init__.py
  dbgpt/model/__init__.py
  dbgpt/model/adapter/base.py
  dbgpt/model/adapter/hf_adapter.py
  dbgpt/model/cluster/base.py
  dbgpt/model/cluster/client.py
  dbgpt/model/cluster/worker/default_worker.py
  dbgpt/model/cluster/worker/remote_worker.py
  dbgpt/model/operator/__init__.py
  dbgpt/model/operator/llm_operator.py
  dbgpt/model/operator/model_operator.py
  dbgpt/model/proxy/llms/bard.py
  dbgpt/model/proxy/llms/chatgpt.py
  dbgpt/model/proxy/llms/gemini.py
  dbgpt/model/proxy/llms/spark.py
  dbgpt/model/proxy/llms/tongyi.py
  dbgpt/model/proxy/llms/wenxin.py
  dbgpt/model/proxy/llms/zhipu.py
  dbgpt/model/utils/chatgpt_utils.py
  dbgpt/serve/conversation/operator.py
  dbgpt/serve/core/serve.py
  dbgpt/util/function_utils.py
  dbgpt/util/prompt_util.py
  dbgpt/util/tests/test_function_utils.py
  examples/awel/data_analyst_assistant.py
  examples/awel/simple_chat_history_example.py
  examples/awel/simple_dag_example.py
  examples/awel/simple_llm_client_example.py
  examples/sdk/simple_sdk_llm_example.py
  examples/sdk/simple_sdk_llm_sql_example.py
  setup.py
Labels: enhancement

#1046 chore: update wechat QRcode
  assets/wechat.jpg
Labels: internal

#1044 feat(agent): Multi agents v0.1
  .gitignore
  dbgpt/agent/agents/agent.py
  dbgpt/agent/agents/agents_mange.py
  dbgpt/agent/agents/base_agent.py
  dbgpt/agent/agents/base_team.py
  dbgpt/agent/agents/expand/plugin_assistant_agent.py
  dbgpt/agent/agents/expand/summary_assistant_agent.py
  dbgpt/agent/agents/plan_group_chat.py
  dbgpt/agent/plugin/commands/command.py
  dbgpt/agent/plugin/commands/command_mange.py
  dbgpt/agent/plugin/loader.py
  dbgpt/agent/plugin/plugin.py
  dbgpt/app/dbgpt_server.py
  dbgpt/app/static/swagger-ui-bundle.js
  dbgpt/app/static/swagger-ui.css
  dbgpt/model/compression.py
  dbgpt/serve/agent/agents/controller.py
  dbgpt/serve/agent/agents/db_gpts_memory.py
  dbgpt/serve/agent/team/__init__.py
  dbgpt/serve/agent/team/base.py
  dbgpt/serve/agent/team/layout/__init__.py
  dbgpt/serve/agent/team/layout/agent_operator.py
  dbgpt/serve/agent/team/layout/team_awel_layout.py
  dbgpt/serve/agent/team/plan/__init__.py
  dbgpt/serve/agent/team/plan/planner_agent.py
  dbgpt/serve/agent/team/plan/team_auto_plan.py
  dbgpt/vis/__init__.py
  dbgpt/vis/base.py
  dbgpt/vis/client.py
  dbgpt/vis/tags/__init__.py
  dbgpt/vis/tags/vis_agent_message.py
  dbgpt/vis/tags/vis_agent_plans.py
  dbgpt/vis/tags/vis_chart.py
  dbgpt/vis/tags/vis_code.py
  dbgpt/vis/tags/vis_dashboard.py
  dbgpt/vis/tags/vis_plugin.py
  examples/agents/awel_layout_agents_chat_examples.py
  examples/agents/plugin_agent_dialogue_example.py
  examples/awel/simple_rag_example.py
  examples/notebook/agent_awel_layout_dialogue_example.ipynb
  examples/test_files/DB-GPT-Plugins-main-20231117140550.zip
Labels: enhancement, agent

#1053 feat(agent): Add summary assistant checking
  dbgpt/agent/agents/expand/summary_assistant_agent.py
  examples/agents/single_summary_agent_dialogue_example.py
Labels: enhancement, agent

#1061 feat(RAG):add rag operators and rag awel examples
  dbgpt/rag/extractor/summary.py
  dbgpt/rag/operator/db_schema.py
  dbgpt/rag/operator/embedding.py
  dbgpt/rag/operator/knowledge.py
  dbgpt/rag/operator/rerank.py
  dbgpt/rag/operator/rewrite.py
  dbgpt/rag/operator/summary.py
  dbgpt/rag/retriever/db_schema.py
  dbgpt/rag/retriever/embedding.py
  dbgpt/rag/retriever/rewrite.py
  dbgpt/rag/retriever/tests/test_db_struct.py
  dbgpt/rag/summary/db_summary_client.py
  dbgpt/rag/text_splitter/token_splitter.py
  dbgpt/serve/rag/assembler/db_schema.py
  dbgpt/serve/rag/assembler/embedding.py
  dbgpt/serve/rag/assembler/summary.py
  dbgpt/serve/rag/assembler/tests/test_embedding_assembler.py
  dbgpt/serve/rag/operators/__init__.py
  dbgpt/serve/rag/operators/base.py
  dbgpt/serve/rag/operators/db_schema.py
  dbgpt/serve/rag/operators/embedding.py
  dbgpt/storage/vector_store/connector.py
  examples/awel/simple_dbschema_retriever_example.py
  examples/awel/simple_rag_embedding_example.py
  examples/awel/simple_rag_retriever_example.py
  examples/awel/simple_rag_rewrite_example.py
  examples/awel/simple_rag_summary_example.py
  examples/rag/db_schema_rag_example.py
  examples/rag/embedding_rag_example.py
Labels: enhancement

#1069 chore: update wechat QR code
  assets/wechat.jpg
Labels: internal

#1073 fix:update awel embedding examples and delete unuseful code.
  dbgpt/app/component_configs.py
  dbgpt/app/knowledge/service.py
  dbgpt/rag/graph/graph_engine.py
  dbgpt/rag/graph/graph_factory.py
  dbgpt/rag/graph/graph_search.py
  dbgpt/rag/graph/index_struct.py
  dbgpt/rag/graph/index_type.py
  dbgpt/rag/graph/kv_index.py
  dbgpt/rag/graph/node.py
  dbgpt/rag/graph/search.py
  examples/awel/simple_rag_embedding_example.py
Labels: fix

#1077 chore: Format agent code
  CONTRIBUTING.md
  dbgpt/agent/agents/agents_mange.py
  dbgpt/agent/agents/expand/plugin_assistant_agent.py
  dbgpt/agent/agents/expand/retrieve_summary_assistant_agent.py
  dbgpt/agent/agents/expand/summary_assistant_agent.py
  dbgpt/agent/agents/resource.py
  dbgpt/agent/common/schema.py
  dbgpt/agent/memory/gpts_memory.py
  dbgpt/app/openapi/api_v1/api_v1.py
  dbgpt/serve/agent/agents/controller.py
  dbgpt/serve/agent/db/gpts_manage_db.py
  dbgpt/vis/tags/vis_gpts_result.py
Labels: internal

#1083 feat: UI component rendering in agent dialog mode
  dbgpt/app/static/404.html
  dbgpt/app/static/404/index.html
  dbgpt/app/static/_next/static/bNfEORAhR_LQn6V50o552/_buildManifest.js
  dbgpt/app/static/_next/static/bNfEORAhR_LQn6V50o552/_ssgManifest.js
  dbgpt/app/static/_next/static/chunks/134.1d06cc0663735371.js
  dbgpt/app/static/_next/static/chunks/341.9dc08d6acf941db1.js
  dbgpt/app/static/_next/static/chunks/739.c531bc8e1d8566bc.js
  dbgpt/app/static/_next/static/chunks/932.2a50a35c55e19f03.js
  dbgpt/app/static/_next/static/chunks/947-5980a3ff49069ddd.js
  dbgpt/app/static/_next/static/chunks/pages/_app-0812c1bce27ce0fa.js
  dbgpt/app/static/_next/static/chunks/pages/chat-a869c66578892120.js
  dbgpt/app/static/_next/static/chunks/pages/index-06183caf17230eba.js
  dbgpt/app/static/_next/static/chunks/webpack-e58f0bdf52ce1468.js
  dbgpt/app/static/_next/static/css/9a8743052c8f63f7.css
  dbgpt/app/static/agent/index.html
  dbgpt/app/static/chat/index.html
  dbgpt/app/static/database/index.html
  dbgpt/app/static/index.html
  dbgpt/app/static/knowledge/chunk/index.html
  dbgpt/app/static/knowledge/index.html
  dbgpt/app/static/models/index.html
  dbgpt/app/static/prompt/index.html
  web/app/chat-context.tsx
  web/app/i18n.ts
  web/client/api/request.ts
  web/components/chart/autoChart/index.tsx
  web/components/chat/agent-content.tsx
  web/components/chat/chat-container.tsx
  web/components/chat/chat-content/agent-messages.tsx
  web/components/chat/chat-content/agent-plans.tsx
  web/components/chat/chat-content/chart-view.tsx
  web/components/chat/chat-content/code-preview.tsx
  web/components/chat/chat-content/config.tsx
  web/components/chat/chat-content/vis-chart.tsx
  web/components/chat/chat-content/vis-code.tsx
  web/components/chat/chat-content/vis-convert-error.tsx
  web/components/chat/chat-content/vis-dashboard.tsx
  web/components/chat/chat-content/vis-plugin.tsx
  web/components/chat/completion.tsx
  web/components/chat/header/agent-selector.tsx
  web/components/layout/side-bar.tsx
  web/hooks/use-chat.ts
  web/package-lock.json
  web/package.json
  web/types/agent.ts
  web/types/chat.ts
Labels: enhancement

#1092 refactor: Refactor for core SDK
  Makefile
  dbgpt/__init__.py
  dbgpt/_version.py
  dbgpt/agent/agents/expand/retrieve_summary_assistant_agent.py
  dbgpt/app/chat_adapter.py
  dbgpt/app/scene/base_chat.py
  dbgpt/app/scene/operator/app_operator.py
  dbgpt/component.py
  dbgpt/core/awel/__init__.py
  dbgpt/core/awel/operator/base.py
  dbgpt/core/awel/task/base.py
  dbgpt/core/awel/task/task_impl.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/core/awel/trigger/trigger_manager.py
  dbgpt/core/interface/operator/composer_operator.py
  dbgpt/core/interface/operator/prompt_operator.py
  dbgpt/model/__init__.py
  dbgpt/model/adapter/loader.py
  dbgpt/model/adapter/old_adapter.py
  dbgpt/model/base.py
  dbgpt/model/cluster/worker/default_worker.py
  dbgpt/model/cluster/worker/embedding_worker.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/model/llm/compression.py
  dbgpt/model/llm/conversation.py
  dbgpt/model/llm/inference.py
  dbgpt/model/operator/__init__.py
  dbgpt/model/operator/llm_operator.py
  dbgpt/model/parameter.py
  dbgpt/model/utils/llm_utils.py
  dbgpt/serve/agent/team/layout/team_awel_layout.py
  examples/agents/auto_plan_agent_dialogue_example.py
  examples/agents/awel_layout_agents_chat_examples.py
  examples/agents/plugin_agent_dialogue_example.py
  examples/agents/retrieve_summary_agent_dialogue_example.py
  examples/agents/single_agent_dialogue_example.py
  examples/agents/single_summary_agent_dialogue_example.py
  examples/awel/simple_rag_retriever_example.py
  examples/awel/simple_rag_rewrite_example.py
  examples/awel/simple_rag_summary_example.py
  examples/rag/rewrite_rag_example.py
  examples/rag/summary_extractor_example.py
  examples/sdk/simple_sdk_llm_example.py
  examples/sdk/simple_sdk_llm_sql_example.py
  setup.py
Labels: internal

#1081 feat: add schema-linking awel example
  dbgpt/rag/operator/schema_linking.py
  dbgpt/rag/schemalinker/__init__.py
  dbgpt/rag/schemalinker/base_linker.py
  dbgpt/rag/schemalinker/schema_linking.py
  examples/awel/simple_nl_schema_sql_chart_example.py
Labels: enhancement

#1097 docs: readme update & contact
  README.md
  README.zh.md
  assets/dbgpt.png
  assets/roadmap.jpg
  assets/wechat.jpg
  examples/awel/simple_nl_schema_sql_chart_example.py
Labels: documentation

#1099 chore: Fix package name conflict error
  dbgpt/app/scene/base_chat.py
  dbgpt/app/scene/operators/__init__.py
  dbgpt/app/scene/operators/app_operator.py
  dbgpt/core/awel/__init__.py
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/operators/__init__.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/operators/common_operator.py
  dbgpt/core/awel/operators/stream_operator.py
  dbgpt/core/awel/runner/job_manager.py
  dbgpt/core/awel/runner/local_runner.py
  dbgpt/core/awel/trigger/base.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/core/interface/operators/__init__.py
  dbgpt/core/interface/operators/composer_operator.py
  dbgpt/core/interface/operators/llm_operator.py
  dbgpt/core/interface/operators/message_operator.py
  dbgpt/core/interface/operators/prompt_operator.py
  dbgpt/core/interface/operators/retriever.py
  dbgpt/core/operators/__init__.py
  dbgpt/datasource/operators/__init__.py
  dbgpt/datasource/operators/datasource_operator.py
  dbgpt/model/operators/__init__.py
  dbgpt/model/operators/llm_operator.py
  dbgpt/model/utils/chatgpt_utils.py
  dbgpt/rag/operators/__init__.py
  dbgpt/rag/operators/datasource.py
  dbgpt/rag/operators/db_schema.py
  dbgpt/rag/operators/embedding.py
  dbgpt/rag/operators/knowledge.py
  dbgpt/rag/operators/rerank.py
  dbgpt/rag/operators/rewrite.py
  dbgpt/rag/operators/schema_linking.py
  dbgpt/rag/operators/summary.py
  dbgpt/serve/conversation/operator.py
  examples/awel/data_analyst_assistant.py
  examples/awel/simple_chat_dag_example.py
  examples/awel/simple_chat_history_example.py
  examples/awel/simple_dbschema_retriever_example.py
  examples/awel/simple_llm_client_example.py
  examples/awel/simple_nl_schema_sql_chart_example.py
  examples/awel/simple_rag_embedding_example.py
  examples/awel/simple_rag_retriever_example.py
  examples/awel/simple_rag_rewrite_example.py
  examples/awel/simple_rag_summary_example.py
  examples/sdk/simple_sdk_llm_example.py
  examples/sdk/simple_sdk_llm_sql_example.py
  setup.py
Labels: internal

#1102 fix(core): Fix bug of sharing data across DAGs
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/runner/local_runner.py
  dbgpt/core/awel/trigger/http_trigger.py
Labels: fix, core

#1111 chore: add contributor wall
  README.md
  README.zh.md
Labels: internal

#1112 fix: Fix examples/awel get model_name from model_config
  examples/awel/simple_dbschema_retriever_example.py
  examples/awel/simple_rag_embedding_example.py
  examples/awel/simple_rag_retriever_example.py
Labels: fix

#1105 feat: add Jina Embeddings
  dbgpt/rag/embedding/embeddings.py
Labels: enhancement

#1117 fix:default setting prompt with history messages
  dbgpt/core/interface/operators/message_operator.py
  dbgpt/storage/vector_store/milvus_store.py
Labels: fix

#1129 docs: Add documents for dbgpt core lib
  .github/workflows/pylint.yml
  Makefile
  README.zh.md
  assets/wechat.jpg
  docs/docs/application/started_tutorial/agents/crawl_data_analysis_agents.md
  docs/docs/application/started_tutorial/agents/db_data_analysis_agents.md
  docs/docs/application/started_tutorial/agents/plugin.md
  docs/docs/awel/awel.md
  docs/docs/awel/cookbook/data_analysis_use_awel.md
  docs/docs/awel/cookbook/multi_round_chat_withllm.md
  docs/docs/awel/cookbook/quickstart_basic_awel_workflow.md
  docs/docs/awel/cookbook/sql_awel_use_rag_and_schema_linking.md
  docs/docs/awel/get_started.ipynb
  docs/docs/awel/get_started.md
  docs/docs/awel/how_to/operator/join.md
  docs/docs/awel/how_to/operator/map.md
  docs/docs/awel/how_to/operator/reduce.md
  docs/docs/awel/how_to/operator/streamify_abs_operator.md
  docs/docs/awel/how_to/operator/trigger.md
  docs/docs/awel/how_to/workflow/dag_pipeline.md
  docs/docs/awel/why_use_awel.md
  docs/docs/faq/install.md
  docs/docs/faq/kbqa.md
  docs/docs/faq/llm.md
  docs/sidebars.js
  docs/static/img/agents/agent_scene.png
  docs/static/img/agents/code_agent.png
  docs/static/img/agents/crawl_agent.png
  docs/static/img/agents/crawl_agent_issue.png
  docs/static/img/agents/data_agents_charts.png
  docs/static/img/agents/data_agents_gif.gif
  docs/static/img/agents/data_analysis_agent.png
  docs/static/img/cli/cli_m.gif
  docs/static/img/cli/kbqa.gif
  docs/static/img/cli/kd_new.gif
  docs/static/img/cli/start_cli_new.gif
  examples/agents/auto_plan_agent_dialogue_example.py
Labels: documentation

#1133 fix: MySQL Database not support DDL init and upgrade.
  dbgpt/app/base.py
  dbgpt/storage/vector_store/milvus_store.py
  docs/docs/installation/sourcecode.md
  examples/rag/simple_dbschema_retriever_example.py
  examples/rag/simple_rag_embedding_example.py
  examples/rag/simple_rag_retriever_example.py
Labels: fix
