Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-08, with the labels that each got.

#1767 fix(ChatKnowledge): Fix knowledge command load bug
  dbgpt/app/knowledge/_cli/knowledge_client.py
  dbgpt/app/knowledge/request/request.py
  dbgpt/serve/rag/service/service.py
Labels: fix, ChatKnowledge

#1766 feat(model): Support mistral nemo
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1757 feat:add financial report how to use doc.
  docs/docs/application/started_tutorial/chat_financial_report.md
  docs/docs/awel/cookbook/first_rag_with_awel.md
  docs/static/img/chat_knowledge/fin_report/chat.jpg
  docs/static/img/chat_knowledge/fin_report/financial_robot_chat.png
  docs/static/img/chat_knowledge/fin_report/financial_space.png
  docs/static/img/chat_knowledge/fin_report/knowledge_workflow.png
Labels: enhancement

#1772 fix(chatgpt): Resolve async response issue with Azure GPT-4o API
  dbgpt/model/proxy/llms/chatgpt.py
Labels: fix

#1765 fix: Editor page with redundant table fields of the same name in othe…
  dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
  dbgpt/datasource/rdbms/base.py
  dbgpt/datasource/rdbms/conn_clickhouse.py
  dbgpt/datasource/rdbms/conn_doris.py
  dbgpt/datasource/rdbms/conn_postgresql.py
  dbgpt/datasource/rdbms/conn_sqlite.py
  dbgpt/datasource/rdbms/conn_vertica.py
Labels: fix

#1784 fix: Fix knowledge api report error when call create space api
  dbgpt/client/schema.py
Labels: fix

#1787 fix: add ding group & update wechat
  README.zh.md
  assets/ding.jpg
  assets/wechat.jpg
Labels: fix

#1797 feat: add Select type node rendering based on AWEL2.0 protocol to workflow
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/cascader.tsx
  web/components/flow/node-renderer/index.ts
  web/components/flow/node-renderer/select.tsx
  web/types/flow.ts
Labels: enhancement

#1794 fix(knowledge API): Unique Constraint Issue with create_space API Cau…
  dbgpt/serve/rag/service/service.py
Labels: fix

#1807 fix(ci): Fix pylint check error
  dbgpt/serve/rag/service/service.py
Labels: fix

#1810 feat: update code of awel-flow2.0 branch
  .env.template
  README.zh.md
  assets/ding.jpg
  assets/wechat.jpg
  dbgpt/_private/config.py
  dbgpt/app/initialization/db_model_initialization.py
  dbgpt/app/initialization/serve_initialization.py
  dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
  dbgpt/client/schema.py
  dbgpt/component.py
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/flow/__init__.py
  dbgpt/core/awel/flow/base.py
  dbgpt/core/awel/flow/tests/test_flow_variables.py
  dbgpt/core/awel/flow/ui.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/tests/conftest.py
  dbgpt/core/awel/tests/test_dag_variables.py
  dbgpt/core/awel/util/parameter_util.py
  dbgpt/core/interface/storage.py
  dbgpt/core/interface/tests/test_variables.py
  dbgpt/core/interface/variables.py
  dbgpt/datasource/rdbms/base.py
  dbgpt/datasource/rdbms/conn_clickhouse.py
  dbgpt/datasource/rdbms/conn_doris.py
  dbgpt/datasource/rdbms/conn_postgresql.py
  dbgpt/datasource/rdbms/conn_sqlite.py
  dbgpt/datasource/rdbms/conn_vertica.py
  dbgpt/serve/core/__init__.py
  dbgpt/serve/flow/api/endpoints.py
  dbgpt/serve/flow/api/schemas.py
  dbgpt/serve/flow/api/variables_provider.py
  dbgpt/serve/flow/config.py
  dbgpt/serve/flow/models/models.py
  dbgpt/serve/flow/models/variables_adapter.py
  dbgpt/serve/flow/serve.py
  dbgpt/serve/flow/service/variables_service.py
  dbgpt/serve/rag/service/service.py
  examples/awel/awel_flow_ui_components.py
  setup.py
Labels: enhancement

#1816 feat: add atom component to flow(textArea、treeSelect、timePiceker、slider)
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/index.ts
  web/components/flow/node-renderer/slider.tsx
  web/components/flow/node-renderer/sliderList.tsx
  web/components/flow/node-renderer/textarea.tsx
  web/components/flow/node-renderer/timePicker.tsx
  web/components/flow/node-renderer/treeSelect.tsx
  web/types/flow.ts
  web/utils/flow.ts
Labels: enhancement

#1830 fix: fixed the issue of incorrect background color of canvas node in dark mode
  web/components/flow/canvas-node.tsx
  web/components/flow/node-handler.tsx
  web/components/flow/node-renderer/date-picker.tsx
  web/components/flow/node-renderer/time-picker.tsx
Labels: fix

#1831 feat: add Password component to flow
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/index.ts
  web/components/flow/node-renderer/input.tsx
  web/components/flow/node-renderer/password.tsx
Labels: enhancement

#1832 chore: update backend api
  dbgpt/core/awel/flow/ui.py
  dbgpt/serve/flow/api/endpoints.py
  dbgpt/serve/flow/api/schemas.py
  examples/awel/awel_flow_ui_components.py
Labels: internal

#1808 fix: Fix can't read the milvus url config
  dbgpt/storage/vector_store/milvus_store.py
Labels: fix

#1834 feat: add atom components to flow (upload、codeEditor)
  web/app/i18n.ts
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/codeEditor.tsx
  web/components/flow/node-renderer/index.ts
  web/components/flow/node-renderer/textarea.tsx
  web/components/flow/node-renderer/tree-select.tsx
  web/components/flow/node-renderer/upload.tsx
  web/types/flow.ts
  web/utils/request.ts
Labels: enhancement

#1836 fix: 1、components treeSelect and Password switch locations 2、remove console
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/date-picker.tsx
Labels: fix

#1837 fix: Components slider and treeSelect drag
  web/components/flow/node-renderer/slider.tsx
  web/components/flow/node-renderer/tree-select.tsx
Labels: fix

#1839 feat: add Variables component to flow
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/index.ts
  web/components/flow/node-renderer/variables.tsx
Labels: enhancement

#1846 feat: TextArea component support mouse scrolling、Slider component support range
  web/components/flow/node-renderer/slider.tsx
  web/components/flow/node-renderer/textarea.tsx
Labels: enhancement

#1847 fix: add label of component
  web/components/flow/node-param-handler.tsx
Labels: fix

#1848 chore: update api
  dbgpt/core/interface/file.py
  dbgpt/serve/flow/api/endpoints.py
  examples/awel/awel_flow_ui_components.py
Labels: internal

#1850 feat: update UI components for better user experience
  web/client/api/request.ts
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/codeEditor.tsx
  web/components/flow/node-renderer/date-picker.tsx
  web/components/flow/node-renderer/password.tsx
  web/components/flow/node-renderer/slider.tsx
  web/components/flow/node-renderer/textarea.tsx
  web/components/flow/node-renderer/time-picker.tsx
  web/components/flow/node-renderer/tree-select.tsx
  web/components/flow/node-renderer/upload.tsx
  web/pages/flow/canvas/index.tsx
  web/types/flow.ts
Labels: enhancement

#1851 chore: update api
  web/client/api/request.ts
  web/types/flow.ts
Labels: internal

#1849 chore:wechat update
  assets/wechat.jpg
Labels: internal

#1856 feat: update canvasNode component to support parameter refreshing
  web/client/api/request.ts
  web/components/flow/canvas-node.tsx
  web/components/flow/node-handler.tsx
  web/components/flow/node-param-handler.tsx
  web/types/flow.ts
  web/utils/flow.ts
Labels: enhancement

#1858 feat: add prefix icon support to RenderInput component
  web/components/flow/node-renderer/input.tsx
Labels: enhancement

#1861 refactor: fix import typo in node-renderer/index.ts
  web/app/i18n.ts
  web/components/flow/canvas-node.tsx
  web/components/flow/node-handler.tsx
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/cascader.tsx
  web/components/flow/node-renderer/checkbox.tsx
  web/components/flow/node-renderer/code-editor.tsx
  web/components/flow/node-renderer/codeEditor.tsx
  web/components/flow/node-renderer/date-picker.tsx
  web/components/flow/node-renderer/index.ts
  web/components/flow/node-renderer/input.tsx
  web/components/flow/node-renderer/password.tsx
  web/components/flow/node-renderer/radio.tsx
  web/components/flow/node-renderer/select.tsx
  web/components/flow/node-renderer/slider.tsx
  web/components/flow/node-renderer/textarea.tsx
  web/components/flow/node-renderer/time-picker.tsx
  web/components/flow/node-renderer/tree-select.tsx
  web/components/flow/node-renderer/upload.tsx
  web/components/flow/node-renderer/variables.tsx
Labels: internal

#1877 refactor: Update import statement for isFileDb in form-dialog.tsx
  web/components/database/form-dialog.tsx
Labels: internal

#1871 refactor: upgrade gpt-vis
  web/components/chat/agent-content.tsx
  web/components/chat/chat-content/VisResponse.tsx
  web/components/chat/chat-content/agent-messages.tsx
  web/components/chat/chat-content/agent-plans.tsx
  web/components/chat/chat-content/config.tsx
  web/components/chat/chat-content/index.tsx
  web/components/chat/chat-content/vis-code.tsx
  web/components/chat/chat-content/vis-plugin.tsx
  web/new-components/chat/content/ChatContent.tsx
  web/new-components/common/MarkdownContext.tsx
  web/package.json
Labels: internal

#1878 feat: Update import statement for isFileDb in form-dialog.tsx
  web/components/flow/add-nodes-sider.tsx
  web/components/flow/add-nodes.tsx
  web/new-components/chat/sider/ChatSider.tsx
  web/pages/construct/flow/canvas/index.tsx
Labels: enhancement

#1887 refactor: Update Collapse component styling in add-nodes-sider.tsx
  web/components/flow/add-nodes-sider.tsx
  web/components/flow/canvas-modal/export-flow-modal.tsx
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-modal/save-flow-modal.tsx
  web/components/flow/static-nodes.tsx
  web/locales/en/flow.ts
  web/locales/zh/chat.ts
  web/locales/zh/flow.ts
  web/pages/construct/flow/canvas/index.tsx
Labels: internal

#1895 chore: merge frontend code of branch dev-0.6
  web/app/i18n.ts
  web/client/api/app/index.ts
  web/client/api/flow/index.ts
  web/client/api/request.ts
  web/components/chat/completion.tsx
  web/components/database/form-dialog.tsx
  web/components/flow/add-nodes-sider.tsx
  web/components/flow/add-nodes.tsx
  web/components/flow/canvas-modal/export-flow-modal.tsx
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-modal/save-flow-modal.tsx
  web/components/flow/canvas-node.tsx
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/slider.tsx
  web/components/flow/node-renderer/time-picker.tsx
  web/components/flow/node-renderer/upload.tsx
  web/components/flow/static-nodes.tsx
  web/locales/en/chat.ts
  web/locales/en/common.ts
  web/locales/en/flow.ts
  web/locales/en/index.ts
  web/locales/zh/chat.ts
  web/locales/zh/common.ts
  web/locales/zh/flow.ts
  web/locales/zh/index.ts
  web/new-components/chat/sider/ChatSider.tsx
  web/package.json
  web/pages/_app.tsx
  web/pages/agent/index.tsx
  web/pages/app/index.tsx
  web/pages/construct/database.tsx
  web/pages/construct/flow/canvas/index.tsx
  web/pages/construct/flow/index.tsx
  web/pages/database/index.tsx
  web/pages/flow/canvas/index.tsx
  web/pages/flow/index.tsx
  web/pages/knowledge/chunk/index.tsx
  web/pages/knowledge/graph/index.tsx
  web/pages/knowledge/index.tsx
  web/pages/models/index.tsx
  web/pages/prompt/index.tsx
  web/types/flow.ts
  web/yarn.lock
Labels: internal

#1900 fix: remove tooltip
  web/components/flow/node-renderer/slider.tsx
Labels: fix

#1906 fix: Fix position offset while dragging nodes on canvas
  .gitignore
  web/components/flow/add-nodes-sider.tsx
  web/pages/construct/flow/canvas/index.tsx
Labels: fix

#1907 fix: upload Output format String
  web/components/flow/canvas-node.tsx
  web/components/flow/node-renderer/upload.tsx
Labels: fix

#1898 feat(web): AWEL flow 2.0 frontend codes
  .gitignore
  dbgpt/_private/config.py
  web/README.md
  web/client/api/app/index.ts
  web/client/api/flow/index.ts
  web/client/api/request.ts
  web/components/chat/completion.tsx
  web/components/common/gpt-card.tsx
  web/components/database/form-dialog.tsx
  web/components/flow/add-nodes-sider.tsx
  web/components/flow/add-nodes.tsx
  web/components/flow/canvas-modal/export-flow-modal.tsx
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-modal/index.ts
  web/components/flow/canvas-modal/save-flow-modal.tsx
  web/components/flow/canvas-node.tsx
  web/components/flow/node-handler.tsx
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/cascader.tsx
  web/components/flow/node-renderer/checkbox.tsx
  web/components/flow/node-renderer/code-editor.tsx
  web/components/flow/node-renderer/date-picker.tsx
  web/components/flow/node-renderer/index.ts
  web/components/flow/node-renderer/input.tsx
  web/components/flow/node-renderer/password.tsx
  web/components/flow/node-renderer/radio.tsx
  web/components/flow/node-renderer/select.tsx
  web/components/flow/node-renderer/slider.tsx
  web/components/flow/node-renderer/textarea.tsx
  web/components/flow/node-renderer/time-picker.tsx
  web/components/flow/node-renderer/tree-select.tsx
  web/components/flow/node-renderer/upload.tsx
  web/components/flow/node-renderer/variables.tsx
  web/components/flow/static-nodes.tsx
  web/locales/en/chat.ts
  web/locales/en/common.ts
  web/locales/en/flow.ts
  web/locales/en/index.ts
  web/locales/zh/chat.ts
  web/locales/zh/common.ts
  web/locales/zh/flow.ts
  web/locales/zh/index.ts
  web/new-components/chat/sider/ChatSider.tsx
  web/package.json
  web/pages/_app.tsx
  web/pages/agent/index.tsx
  web/pages/app/index.tsx
  web/pages/construct/database.tsx
  web/pages/construct/flow/canvas/index.tsx
  web/pages/construct/flow/index.tsx
  web/pages/database/index.tsx
  web/pages/flow/canvas/index.tsx
  web/pages/flow/index.tsx
  web/pages/knowledge/chunk/index.tsx
  web/pages/knowledge/graph/index.tsx
  web/pages/knowledge/index.tsx
  web/pages/models/index.tsx
  web/pages/prompt/index.tsx
  web/types/flow.ts
  web/utils/flow.ts
Labels: enhancement, web

#1883 refactor: upgrade gpt-vis
  web/components/chat/agent-content.tsx
  web/components/chat/chat-content/VisResponse.tsx
  web/components/chat/chat-content/agent-messages.tsx
  web/components/chat/chat-content/agent-plans.tsx
  web/components/chat/chat-content/config.tsx
  web/components/chat/chat-content/index.tsx
  web/components/chat/chat-content/vis-code.tsx
  web/components/chat/chat-content/vis-plugin.tsx
  web/new-components/chat/content/ChatContent.tsx
  web/new-components/common/MarkdownContext.tsx
  web/next.config.js
  web/package.json
Labels: internal

#1884 fix:graph retrieve bug
  dbgpt/app/scene/chat_knowledge/v1/chat.py
  dbgpt/serve/rag/retriever/knowledge_space.py
  dbgpt/serve/rag/retriever/retriever_chain.py
Labels: fix

#1812 fix(ChatData): Fix execution failure error after manually updating SQL
  web/components/chat/db-editor.tsx
Labels: fix, ChatData

#1914 fix: matching parameters of Upload component、fixed date formatting and Reduced reference
  web/components/flow/canvas-node.tsx
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/date-picker.tsx
  web/components/flow/node-renderer/time-picker.tsx
  web/components/flow/node-renderer/upload.tsx
Labels: fix

#1819 feat(model): Support qianfan embedding and resolves an issue
  .env.template
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/embeddings_loader.py
  dbgpt/model/parameter.py
  dbgpt/rag/embedding/__init__.py
  dbgpt/rag/embedding/embeddings.py
  setup.py
Labels: enhancement, model

#1915 chore: Fix pylint error
  .mypy.ini
  dbgpt/model/adapter/embeddings_loader.py
  dbgpt/model/parameter.py
  dbgpt/rag/embedding/__init__.py
  dbgpt/rag/embedding/embeddings.py
  setup.py
Labels: internal

#1919 fix: Open the popup reset import
  web/components/flow/canvas-modal/import-flow-modal.tsx
Labels: fix

#1924 chore: remove console.log statements
  web/components/chart/index.tsx
  web/components/chat/chat-container.tsx
  web/components/chat/chat-default/index.tsx
  web/components/chat/chat-feedback.tsx
  web/components/database/form-dialog.tsx
  web/components/flow/flow-card.tsx
  web/components/knowledge/RecallTestModal.tsx
  web/components/knowledge/doc-panel.tsx
  web/components/knowledge/segmentation.tsx
  web/pages/construct/knowledge/chunk/index.tsx
  web/pages/evaluation/index.tsx
Labels: internal

#1920 fix: vis-chart is conflict
  docs/docs/agents/introduction/database.md
  docs/docs/agents/introduction/planning.md
  web/components/chat/chat-content/config.tsx
Labels: fix

#1926 chore: update lint config in package.json and fix lint error of web
  web/app/i18n.ts
  web/hooks/use-chat.ts
  web/hooks/use-summary.ts
  web/lib/google-one-tap.ts
  web/lib/session.ts
  web/package.json
  web/types/agent.ts
  web/types/app.ts
  web/types/editor.ts
  web/types/flow.ts
  web/types/prompt.ts
  web/types/userinfo.ts
  web/utils/constants.ts
  web/utils/ctx-axios.ts
  web/utils/flow.ts
  web/utils/index.ts
  web/utils/request.ts
  web/utils/storage.ts
Labels: internal

#1928 fix: build error
  web/lib/dto/models/feedback.dto.ts
  web/next.config.js
  web/package.json
  web/pages/construct/database.tsx
Labels: fix

#1930 chore: update lint config in package.json antd fix lint error
  web/.eslintrc.js
  web/client/api/app/index.ts
  web/client/api/chat/index.ts
  web/client/api/evaluate/index.ts
  web/client/api/index.ts
  web/client/api/knowledge/index.ts
  web/client/api/prompt/index.ts
  web/genAntdCss.ts
  web/locales/en/index.ts
  web/locales/zh/flow.ts
  web/locales/zh/index.ts
  web/new-components/app/AppCard.tsx
  web/new-components/app/TabContent.tsx
  web/new-components/chat/ChatContentContainer.tsx
  web/new-components/chat/content/ChatCompletion.tsx
  web/new-components/chat/content/ChatContent.tsx
  web/new-components/chat/content/ChatDefault.tsx
  web/new-components/chat/content/Feedback.tsx
  web/new-components/chat/content/ModelIcon.tsx
  web/new-components/chat/content/RobotIcon.tsx
  web/new-components/chat/header/ChatHeader.tsx
  web/new-components/chat/input/ChatInput.tsx
  web/new-components/chat/input/ChatInputPanel.tsx
  web/new-components/chat/input/ModelSwitcher.tsx
  web/new-components/chat/input/Resource.tsx
  web/new-components/chat/input/Temperature.tsx
  web/new-components/chat/input/ToolsBar.tsx
  web/new-components/chat/sider/ChatSider.tsx
  web/new-components/common/AppDefaultIcon.tsx
  web/new-components/common/MarkdownContext.tsx
  web/new-components/common/blurredCard/index.tsx
  web/new-components/common/modelSelector/index.tsx
  web/new-components/layout/Construct.tsx
  web/new-components/layout/FloatHelper.tsx
  web/new-components/layout/Header.tsx
  web/new-components/layout/Sider.tsx
  web/new-components/layout/UserBar.tsx
  web/package.json
  web/postcss.config.js
  web/utils/constants/index.ts
Labels: internal
