Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-04, with the labels that each got.

#1359 fix: when delete knowledge, error: space list error embedding is required for MilvusStore
  dbgpt/storage/vector_store/milvus_store.py
Labels: fix

#1363 fix: Fix the default dependency installation error
  setup.py
Labels: fix

#1373 fix: Fix the mypy check error
  .github/workflows/pylint.yml
  dbgpt/app/knowledge/service.py
  dbgpt/storage/vector_store/milvus_store.py
Labels: fix

#1380 fix: dashboard editor run error
  dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
  dbgpt/app/scene/chat_dashboard/data_loader.py
  dbgpt/util/date_utils.py
Labels: fix

#1385 feat(model): Support Qwen1.5-32B
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
  dbgpt/util/date_utils.py
  requirements/dev-requirements.txt
Labels: enhancement, model

#1383 feat: Support HTTP sender
  dbgpt/cli/cli_scripts.py
  dbgpt/core/awel/flow/base.py
  dbgpt/core/awel/flow/flow_factory.py
  dbgpt/core/awel/trigger/ext_http_trigger.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/util/network/__init__.py
  dbgpt/util/network/_cli.py
Labels: enhancement

#1388 chore:wechat update
  assets/wechat.jpg
Labels: internal

#1374 feat: Upgrade torch version to 2.2.1
  docker/base/Dockerfile
  docker/base/build_image.sh
  setup.py
Labels: enhancement

#1391 fix: Resolve the issue of incorrect parameter echo for resources under app editing
  web/components/app/resource-card.tsx
Labels: fix

#1392 docs: update readme content
  README.md
  README.zh.md
Labels: documentation

#1395 feat(RAG):add metadata properties filters
  dbgpt/rag/knowledge/base.py
  dbgpt/rag/knowledge/csv.py
  dbgpt/rag/knowledge/datasource.py
  dbgpt/rag/knowledge/docx.py
  dbgpt/rag/knowledge/factory.py
  dbgpt/rag/knowledge/html.py
  dbgpt/rag/knowledge/markdown.py
  dbgpt/rag/knowledge/pdf.py
  dbgpt/rag/knowledge/pptx.py
  dbgpt/rag/knowledge/string.py
  dbgpt/rag/knowledge/txt.py
  dbgpt/rag/knowledge/url.py
  dbgpt/rag/retriever/base.py
  dbgpt/rag/retriever/db_schema.py
  dbgpt/rag/retriever/embedding.py
  dbgpt/rag/retriever/tests/test_embedding.py
  dbgpt/rag/text_splitter/text_splitter.py
  dbgpt/serve/rag/retriever/knowledge_space.py
  dbgpt/storage/vector_store/base.py
  dbgpt/storage/vector_store/chroma_store.py
  dbgpt/storage/vector_store/connector.py
  dbgpt/storage/vector_store/filters.py
  dbgpt/storage/vector_store/milvus_store.py
  dbgpt/storage/vector_store/pgvector_store.py
  dbgpt/storage/vector_store/weaviate_store.py
  examples/rag/metadata_filter_example.py
Labels: enhancement

#1403 chore:v0.5.4 version and update wechat
  assets/wechat.jpg
  dbgpt/_version.py
  setup.py
Labels: internal

#1404 feat(model): Support moonshot proxy LLM
  .env.template
  .mypy.ini
  dbgpt/_private/config.py
  dbgpt/configs/model_config.py
  dbgpt/core/interface/llm.py
  dbgpt/model/adapter/proxy_adapter.py
  dbgpt/model/proxy/__init__.py
  dbgpt/model/proxy/llms/chatgpt.py
  dbgpt/model/proxy/llms/moonshot.py
Labels: enhancement, model

#1407 feat(agent): Add trace for agent
  dbgpt/agent/core/base_agent.py
  dbgpt/agent/expand/code_assistant_agent.py
  dbgpt/agent/resource/resource_db_api.py
  dbgpt/agent/util/__init__.py
  dbgpt/app/dbgpt_server.py
  dbgpt/component.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/util/tracer/base.py
  dbgpt/util/tracer/span_storage.py
  dbgpt/util/tracer/tests/test_tracer_impl.py
  dbgpt/util/tracer/tracer_impl.py
  dbgpt/vis/__init__.py
  docs/docs/agents/cookbook/calculator_with_agents.md
  docs/docs/agents/custom_agents.md
  docs/sidebars.js
  examples/agents/awel_layout_agents_chat_examples.py
  examples/agents/single_agent_dialogue_example.py
  examples/agents/sql_agent_dialogue_example.py
  setup.py
Labels: enhancement, agent

#1410 refactor: Modify default webserver port to 5670
  .env.template
  dbgpt/_private/config.py
  dbgpt/agent/expand/retrieve_summary_assistant_agent.py
  dbgpt/app/dbgpt_server.py
  dbgpt/app/knowledge/_cli/knowledge_cli.py
  dbgpt/client/client.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/util/benchmarks/llm/llm_benchmarks.py
  dbgpt/util/command_utils.py
  docker-compose.yml
  docker/base/Dockerfile
  docs/docs/api/app.md
  docs/docs/api/chat.md
  docs/docs/api/datasource.md
  docs/docs/api/flow.md
  docs/docs/api/introduction.md
  docs/docs/api/knowledge.md
  docs/docs/application/advanced_tutorial/api.md
  docs/docs/application/advanced_tutorial/cli.md
  docs/docs/awel/get_started.md
  docs/docs/faq/install.md
  docs/docs/installation/docker.md
  docs/docs/installation/docker_compose.md
  docs/docs/installation/sourcecode.md
  docs/docs/quickstart.md
  examples/awel/simple_rag_rewrite_example.py
Labels: internal

#1409 fix rdbms_db_summary
  dbgpt/rag/summary/rdbms_db_summary.py
Labels: fix

#1417 feat(agent): dbgpts support agent
  dbgpt/agent/__init__.py
  dbgpt/agent/core/agent_manage.py
  dbgpt/agent/core/base_agent.py
  dbgpt/agent/plan/awel/agent_operator.py
  dbgpt/agent/plan/awel/agent_operator_resource.py
  dbgpt/app/component_configs.py
  dbgpt/component.py
  dbgpt/serve/agent/agents/controller.py
  dbgpt/serve/agent/app/controller.py
  dbgpt/util/dbgpts/loader.py
  dbgpt/util/dbgpts/repo.py
  dbgpt/util/dbgpts/template.py
Labels: enhancement, agent

#1419 feat: Support retry for 'Chat Data'
  .env.template
  dbgpt/_private/config.py
  dbgpt/app/scene/base_chat.py
  dbgpt/app/scene/chat_db/auto_execute/out_parser.py
  dbgpt/app/scene/exceptions.py
  dbgpt/util/retry.py
Labels: enhancement

#1431 feat(model): Support CodeQwen1.5-7B-Chat
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
Labels: enhancement, model

#1432 fix:[chatdb] clickhouse occur error AttributeError: 'ClickhouseConnect…
  dbgpt/datasource/rdbms/conn_clickhouse.py
Labels: fix

#1436 feat(model): Support Llama-3
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/datasource/rdbms/conn_clickhouse.py
  dbgpt/model/adapter/hf_adapter.py
  dbgpt/model/llm_out/hf_chat_llm.py
  setup.py
Labels: enhancement, model

#1439 feat(model): Support Qwen2MoE
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1442 feat(RAG):add cross-encoder rerank
  dbgpt/rag/retriever/rerank.py
  examples/rag/cross_encoder_rerank_example.py
Labels: enhancement

#1456 feat(RAG):add MRR and HitRate retriever metrics.
  assets/wechat.jpg
  dbgpt/rag/evaluation/retriever.py
  examples/rag/retriever_evaluation_example.py
Labels: enhancement

#1465 fix: Fix oceanbase vector_name_exists bug
  dbgpt/rag/evaluation/retriever.py
  dbgpt/storage/vector_store/oceanbase_store.py
Labels: fix

#1449 fix: Fix parameter type mismatch issue when using Milvus
  dbgpt/storage/vector_store/milvus_store.py
Labels: fix

#1468 chore:v0.5.5 tag
  dbgpt/_version.py
  setup.py
Labels: internal

#1474 feat(model): Qwen110B
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
Labels: enhancement, model

#1475 feat(model): support ollama as an optional llm & embedding proxy
  .mypy.ini
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/embeddings_loader.py
  dbgpt/model/adapter/proxy_adapter.py
  dbgpt/model/parameter.py
  dbgpt/model/proxy/__init__.py
  dbgpt/model/proxy/llms/ollama.py
  dbgpt/rag/embedding/__init__.py
  dbgpt/rag/embedding/embeddings.py
  setup.py
Labels: enhancement, model

#1478 fix: Fix app pydantic error
  dbgpt/serve/agent/app/controller.py
  dbgpt/serve/agent/db/gpts_app.py
Labels: fix
