Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-09, with the labels that each got.

#1935 fix: postgresql read schema_info with characters truncated if too long
  dbgpt/datasource/rdbms/conn_postgresql.py
Labels: fix

#1944 feat: Add AddFlowVariable component for managing flow variables
  web/components/flow/add-flow-variable.tsx
  web/locales/en/flow.ts
  web/locales/zh/flow.ts
  web/new-components/layout/Construct.tsx
  web/pages/construct/flow/canvas/index.tsx
Labels: enhancement

#1942 fix: wechat qrcode expired
  assets/wechat.jpg
Labels: fix

#1952 chore: Remove commented out code for advanced and default modes in flow.ts
  web/client/api/flow/index.ts
  web/components/flow/add-nodes-sider.tsx
  web/components/flow/canvas-node.tsx
  web/locales/en/flow.ts
  web/locales/zh/flow.ts
Labels: internal

#1954 chore: Update AddFlowVariableModal component to include parameter management
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
  web/components/flow/canvas-modal/index.ts
  web/pages/construct/flow/canvas/index.tsx
Labels: internal

#1953 feat(agent):Fix agent bug
  dbgpt/agent/core/action/base.py
  dbgpt/agent/core/action/blank_action.py
  dbgpt/agent/core/agent_manage.py
  dbgpt/agent/core/base_agent.py
  dbgpt/agent/core/plan/plan_action.py
  dbgpt/agent/expand/actions/chart_action.py
  dbgpt/agent/expand/actions/code_action.py
  dbgpt/agent/expand/actions/dashboard_action.py
  dbgpt/agent/expand/actions/indicator_action.py
  dbgpt/agent/expand/actions/tool_action.py
  dbgpt/agent/resource/knowledge.py
  dbgpt/app/openapi/api_v1/api_v1.py
  dbgpt/app/scene/chat_data/chat_excel/excel_analyze/chat.py
  dbgpt/app/scene/chat_data/chat_excel/excel_reader.py
  dbgpt/datasource/manages/connect_config_db.py
  dbgpt/serve/agent/agents/expand/actions/app_start_action.py
  dbgpt/serve/agent/agents/expand/actions/intent_recognition_action.py
  dbgpt/storage/knowledge_graph/community/community_store.py
Labels: enhancement, agent

#1965 feat: upload metadata 、ui size settings 276 320 530 、import flow
  web/client/api/flow/index.ts
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-node.tsx
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/upload.tsx
  web/pages/construct/flow/canvas/index.tsx
  web/styles/globals.css
Labels: enhancement

#1963 feat: Update AddFlowVariableModal component to include parameter management
  web/client/api/flow/index.ts
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-modal/save-flow-modal.tsx
  web/types/flow.ts
Labels: enhancement

#1968 feat: Add support for retrieving keys and variables by key in Flow API
  web/client/api/flow/index.ts
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
  web/tsconfig.json
  web/types/flow.ts
Labels: enhancement

#1972 chore: update api
  .dockerignore
  dbgpt/_private/config.py
  dbgpt/app/initialization/scheduler.py
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/operators/common_operator.py
  dbgpt/model/proxy/base.py
  dbgpt/serve/flow/api/variables_provider.py
  dbgpt/storage/metadata/_base_dao.py
  dbgpt/util/net_utils.py
  dbgpt/util/serialization/check.py
  docker/base/build_image.sh
Labels: internal

#1973 fix: set flow variable default value
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
  web/pages/construct/app/index.tsx
  web/pages/construct/flow/canvas/index.tsx
Labels: fix

#1974 feat: Add helper function to render control component in AddFlowVariableModal
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
Labels: enhancement

#1976 refactor: Update AddFlowVariableModal to use buildVariableString from utils/flow
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
  web/components/flow/canvas-modal/save-flow-modal.tsx
  web/pages/construct/flow/canvas/index.tsx
  web/types/flow.ts
Labels: internal

#1978 refactor: Update AddFlowVariableModal to set a minimum height for the body
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
Labels: internal

#1979 refactor: Update AddFlowVariableModal styles and functionality
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
  web/components/flow/canvas-modal/export-flow-modal.tsx
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-modal/save-flow-modal.tsx
Labels: internal

#1975 feat: Bring In Template
  web/client/api/flow/index.ts
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-modal/index.ts
  web/components/flow/canvas-modal/template-flow-modal.tsx
  web/components/flow/node-renderer/upload.tsx
  web/locales/en/flow.ts
  web/locales/zh/flow.ts
  web/pages/construct/flow/canvas/index.tsx
Labels: enhancement

#1985 feat: flow template add label 、 description
  web/components/flow/canvas-modal/flow-template-modal.tsx
  web/components/flow/canvas-modal/index.ts
  web/locales/en/flow.ts
  web/locales/zh/flow.ts
Labels: enhancement

#1987 fix: Eslint formatting
  web/components/flow/canvas-modal/flow-template-modal.tsx
  web/components/flow/canvas-modal/index.ts
  web/components/flow/canvas-node.tsx
  web/components/flow/node-param-handler.tsx
Labels: fix

#1988 fix: native app bug
  dbgpt/app/openapi/api_v1/api_v1.py
  docker/examples/dashboard/test_case_sqlite_data.py
Labels: fix

#1981 feat(web): Add DAG variables to web flow
  i18n/translate_util.py
  web/client/api/flow/index.ts
  web/components/flow/add-nodes-sider.tsx
  web/components/flow/canvas-modal/add-flow-variable-modal.tsx
  web/components/flow/canvas-modal/export-flow-modal.tsx
  web/components/flow/canvas-modal/flow-template-modal.tsx
  web/components/flow/canvas-modal/import-flow-modal.tsx
  web/components/flow/canvas-modal/index.ts
  web/components/flow/canvas-modal/save-flow-modal.tsx
  web/components/flow/canvas-node.tsx
  web/components/flow/node-param-handler.tsx
  web/components/flow/node-renderer/upload.tsx
  web/locales/en/flow.ts
  web/locales/zh/flow.ts
  web/new-components/layout/Construct.tsx
  web/pages/construct/app/index.tsx
  web/pages/construct/flow/canvas/index.tsx
  web/pages/construct/flow/index.tsx
  web/pages/mobile/chat/components/InputContainer.tsx
  web/styles/globals.css
  web/tsconfig.json
  web/types/flow.ts
  web/utils/flow.ts
Labels: enhancement, web

#1989 fix(ChatKnowledge):full text storage truncate method error.
  dbgpt/storage/full_text/base.py
  dbgpt/storage/vector_store/base.py
Labels: fix, ChatKnowledge

#1991 docs: add v0.6.0 release notes
  assets/wechat.jpg
  docs/blog/2024-09-04-dbgpt-v0.6.0-Defining new standards for AI-native data applications.md
  docs/docs/application/graph_rag.md
  docs/docs/changelog/Released_V0.6.0.md
  docs/static/img/app/graph_rag_display_v0.6.png
  docs/static/img/app/graph_rag_pipeline_v0.6.png
  docs/static/img/app/graph_rag_v0.6.png
  docs/static/img/ft/ft_pipeline.jpg
Labels: documentation

#1997 fix(docs): Fix build doc image error
  docs/Dockerfile-deploy.dockerignore
Labels: fix

#1999 docs: Add flow usage document
  docs/docs/application/awel.md
Labels: documentation

#2000 chore:add v0.6.0 tag
  dbgpt/_version.py
  setup.py
Labels: internal

#2027 docs: adjust graphrag doc
  docs/docs/cookbook/rag/graph_rag_app_develop.md
Labels: documentation

#2018 fix bug - Tongyiproxy embedding model error
  dbgpt/rag/embedding/embeddings.py
Labels: fix

#2028 chore:wechat update
  assets/wechat.jpg
Labels: internal

#2030 feat(model): Support Qwen2.5 models
  README.ja.md
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#2025 fix(model): Fix vllm inference error
  dbgpt/util/parameter_utils.py
Labels: fix, model
