Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-05, with the labels that each got.

#1491 feat(model): Support DeepSeek proxy LLM
  .env.template
  README.zh.md
  dbgpt/_private/config.py
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/proxy_adapter.py
  dbgpt/model/proxy/__init__.py
  dbgpt/model/proxy/llms/deepseek.py
Labels: enhancement, model

#1499 fix(rag): Fix rerank bug of EmbeddingRetriever
  dbgpt/rag/retriever/embedding.py
Labels: fix

#1504 fix(rag): Fix CrossEncoderRanker bug of EmbeddingRetriever
  dbgpt/rag/retriever/rerank.py
  dbgpt/storage/vector_store/chroma_store.py
  dbgpt/storage/vector_store/pgvector_store.py
Labels: fix

#1511 fix: Upgrade spacy model
  dbgpt/storage/vector_store/chroma_store.py
  docker/base/Dockerfile
Labels: fix

#1508 feat:chroma store refactor
  dbgpt/_version.py
  dbgpt/app/knowledge/service.py
  dbgpt/storage/vector_store/base.py
  dbgpt/storage/vector_store/chroma_store.py
  dbgpt/storage/vector_store/pgvector_store.py
  setup.py
Labels: enhancement

#1516 feat(model): Support Yi-1.5 models
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/base.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1517 chore: wechat update
  assets/wechat.jpg
Labels: internal

#1500 feat: ES VectorStore
  .env.template
  .mypy.ini
  dbgpt/_private/config.py
  dbgpt/app/knowledge/service.py
  dbgpt/storage/vector_store/__init__.py
  dbgpt/storage/vector_store/elastic_store.py
Labels: enhancement

#1522 feat(model): Support deploy rerank model
  .env.template
  dbgpt/_private/config.py
  dbgpt/agent/expand/resources/host_tool.py
  dbgpt/app/base.py
  dbgpt/app/component_configs.py
  dbgpt/app/dbgpt_server.py
  dbgpt/app/initialization/embedding_component.py
  dbgpt/app/scene/chat_knowledge/v1/chat.py
  dbgpt/configs/model_config.py
  dbgpt/core/__init__.py
  dbgpt/core/interface/embeddings.py
  dbgpt/core/schema/api.py
  dbgpt/model/adapter/embeddings_loader.py
  dbgpt/model/adapter/model_adapter.py
  dbgpt/model/cluster/apiserver/api.py
  dbgpt/model/cluster/base.py
  dbgpt/model/cluster/embedding/remote_embedding.py
  dbgpt/model/cluster/worker/embedding_worker.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/model/parameter.py
  dbgpt/rag/embedding/__init__.py
  dbgpt/rag/embedding/embedding_factory.py
  dbgpt/rag/embedding/embeddings.py
  dbgpt/rag/embedding/rerank.py
  dbgpt/rag/retriever/embedding.py
  dbgpt/rag/retriever/rerank.py
  docs/docs/installation/advanced_usage/OpenAI_SDK_call.md
  docs/docs/installation/model_service/cluster.md
  requirements/lint-requirements.txt
Labels: enhancement, model

#1527 feat: Support resource for dbgpts
  assets/schema/upgrade/v_0_5_6/upgrade_to_v0.5.6.sql
  assets/schema/upgrade/v_0_5_6/v0.5.5.sql
  dbgpt/agent/expand/actions/tool_action.py
  dbgpt/agent/resource/manage.py
  dbgpt/util/dbgpts/base.py
  dbgpt/util/dbgpts/loader.py
  dbgpt/util/dbgpts/template.py
Labels: enhancement

#1529 fix(build): Fix build allinone images error
  docker/allinone/Dockerfile
Labels: fix

#1532 fix:multi client error
  dbgpt/storage/vector_store/connector.py
Labels: fix

#1533 fix: delete datasource bug
  dbgpt/storage/vector_store/connector.py
Labels: fix

#1538 feat: Add support for Vertica analytical database
  dbgpt/app/static/_next/static/chunks/pages/_app-9004512aa620d772.js
  dbgpt/app/static/database/index.html
  dbgpt/app/static/icons/vertica.png
  dbgpt/datasource/manages/connector_manager.py
  dbgpt/datasource/rdbms/conn_vertica.py
  dbgpt/datasource/rdbms/dialect/vertica/base.py
  dbgpt/datasource/rdbms/dialect/vertica/dialect_vertica_python.py
  dbgpt/storage/schema.py
  docker/examples/sqls/case_1_student_manager_vertica.sql
  docker/examples/sqls/case_2_ecom_vertica.sql
  docker/examples/sqls/test_case_info_vertica.sql
  docs/docs/modules/connections.md
  setup.py
  web/public/icons/vertica.png
  web/types/db.ts
  web/utils/constants.ts
Labels: enhancement

#1537 feat(model): Support DeepSeek v2 lite model
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
  scripts/setup_autodl_env.sh
Labels: enhancement, model

#1543 feat(model): Support Yi 1.5 16k models
  dbgpt/configs/model_config.py
Labels: enhancement, model

#1544 chore:update wechat
  assets/wechat.jpg
Labels: internal

#1545 fix: wrong default value of parameter parallel_executions for async_retry
  dbgpt/app/scene/base_chat.py
Labels: fix

#1540 fix(agent): Remove resources of planner agent
  dbgpt/agent/core/plan/planner_agent.py
  dbgpt/serve/agent/agents/controller.py
Labels: fix, agent

#1554 feat(model): Support Phi-3 models
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
  dbgpt/model/llm_out/hf_chat_llm.py
Labels: enhancement, model

#1548 fix(ChatKnowledge): add aload_document
  dbgpt/app/knowledge/api.py
  dbgpt/app/knowledge/service.py
  dbgpt/rag/assembler/embedding.py
  dbgpt/rag/index/base.py
  dbgpt/serve/rag/service/service.py
  dbgpt/storage/knowledge_graph/knowledge_graph.py
  dbgpt/storage/vector_store/base.py
  dbgpt/storage/vector_store/chroma_store.py
  dbgpt/storage/vector_store/connector.py
  dbgpt/storage/vector_store/elastic_store.py
  dbgpt/storage/vector_store/milvus_store.py
  dbgpt/storage/vector_store/oceanbase_store.py
  dbgpt/storage/vector_store/pgvector_store.py
  dbgpt/storage/vector_store/weaviate_store.py
Labels: fix, ChatKnowledge

#1559 feat(model): Support llama-3-sqlcoder-8b
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1564 feat(model): Support openchat-3.6-8b-20240522
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1566 chore:wechat update
  assets/wechat.jpg
Labels: internal

#1573 fix: Fix the problem of multiple line breaks in Q&A
  web/components/common/completion-input.tsx
Labels: fix

#1578 feat(RAG): add BM25 Retriever.
  dbgpt/rag/assembler/bm25.py
  dbgpt/rag/retriever/bm25.py
  examples/rag/bm25_retriever_example.py
Labels: enhancement

#1547 fix(storage): Fix storage connector error
  dbgpt/rag/index/base.py
  dbgpt/storage/vector_store/connector.py
  examples/client/client_chat_example.py
  examples/rag/graph_rag_example.py
Labels: fix
