Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-12, with the labels that each got.

#2170 fix: VectorStore can not be attached to EmbeddingAssemblerOperator bug
  dbgpt/rag/knowledge/pdf.py
  dbgpt/rag/operators/embedding.py
  dbgpt/rag/operators/knowledge.py
  dbgpt/serve/rag/connector.py
  dbgpt/storage/knowledge_graph/community_summary.py
  dbgpt/storage/vector_store/chroma_store.py
  dbgpt/storage/vector_store/elastic_store.py
  dbgpt/storage/vector_store/milvus_store.py
  dbgpt/storage/vector_store/oceanbase_store.py
  dbgpt/storage/vector_store/pgvector_store.py
  dbgpt/storage/vector_store/weaviate_store.py
Labels: fix

#2152 fix sql not found error for chat data
  dbgpt/app/scene/chat_db/auto_execute/out_parser.py
  dbgpt/app/scene/chat_db/auto_execute/prompt.py
Labels: fix

#2175 chore:wechat update
  assets/wechat.jpg
  dbgpt/storage/knowledge_graph/community_summary.py
Labels: internal

#2188 feat(model): Support siliconflow rerank models
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/embeddings_loader.py
  dbgpt/model/parameter.py
  dbgpt/rag/embedding/__init__.py
  dbgpt/rag/embedding/rerank.py
Labels: enhancement, model

#2179 fix: httpx v0.28.0 proxies bug
  dbgpt/model/utils/chatgpt_utils.py
  dbgpt/rag/operators/knowledge.py
Labels: fix

#2194 chore(model): Modify siliconflow name
  .env.template
  dbgpt/_private/config.py
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/embeddings_loader.py
  dbgpt/model/adapter/proxy_adapter.py
  dbgpt/model/parameter.py
  dbgpt/model/proxy/llms/siliconflow.py
  dbgpt/rag/assembler/embedding.py
  dbgpt/rag/embedding/rerank.py
  dbgpt/serve/rag/service/service.py
Labels: internal, model

#2209 docs(graphrag): update TuGraph database version to 4.5.0
  docs/docs/cookbook/rag/graph_rag_app_develop.md
Labels: documentation

#2211 chore: Limit the version of fastapi
  setup.py
Labels: internal

#2213 chore(graphrag): upgrade dbgpt-tugraph-plugins to version 0.1.1
  dbgpt/agent/core/base_agent.py
  dbgpt/app/scene/chat_db/auto_execute/out_parser.py
  dbgpt/storage/graph_store/tugraph_store.py
  setup.py
Labels: internal

#2210 feat:Add Knowledge Process Workflow
  dbgpt/app/operators/rag.py
  dbgpt/core/awel/flow/base.py
  dbgpt/rag/operators/__init__.py
  dbgpt/rag/operators/chunk_manager.py
  dbgpt/rag/operators/full_text.py
  dbgpt/rag/operators/knowledge_graph.py
  dbgpt/rag/operators/process_branch.py
  dbgpt/rag/operators/vector_store.py
  dbgpt/serve/agent/resource/knowledge.py
  dbgpt/serve/flow/templates/en/embedded-knowledge-process-flow-template.json
  dbgpt/serve/flow/templates/en/hybrid-knowledge-process-template.json
  dbgpt/serve/flow/templates/en/kg-knowledge-process-flow-template.json
  dbgpt/serve/flow/templates/zh/embedded-knowledge-process-flow-template.json
  dbgpt/serve/flow/templates/zh/hybrid-knowldge-process-flow-template.json
  dbgpt/serve/flow/templates/zh/kg-knowledge-process-flow-template.json
  dbgpt/serve/rag/api/schemas.py
  dbgpt/serve/rag/service/service.py
  dbgpt/storage/knowledge_graph/community_summary.py
  dbgpt/storage/knowledge_graph/knowledge_graph.py
  docs/docs/awel/awel_tutorial/templates/Embedding.md
  docs/docs/awel/awel_tutorial/templates/Hybrid_Workflow.md
  docs/docs/awel/awel_tutorial/templates/Knowledge_Graph.md
  docs/sidebars.js
Labels: enhancement

#2221 fix(ci): Fix build docker image error
  .github/workflows/docker-image-publish.yml
Labels: fix

#2215 fix(GraphRAG): create same graph name error.
  dbgpt/datasource/conn_tugraph.py
  dbgpt/storage/graph_store/base.py
  dbgpt/storage/graph_store/tugraph_store.py
  dbgpt/storage/knowledge_graph/community_summary.py
  dbgpt/storage/knowledge_graph/knowledge_graph.py
Labels: fix

#2222 feat(ci): Add release pipy workflow
  .github/workflows/python-publish.yml
Labels: enhancement

#2228 docs(graphrag): add oss url for tugraph image
  docs/docs/cookbook/rag/graph_rag_app_develop.md
Labels: documentation

#2229 chore: Upgrade lyric version
  setup.py
Labels: internal

#2230 feat(agent):Agent supports conversation context
  .env.template
  dbgpt/_private/config.py
  dbgpt/agent/core/agent.py
  dbgpt/agent/core/base_agent.py
  dbgpt/agent/core/base_team.py
  dbgpt/agent/core/memory/gpts/base.py
  dbgpt/agent/core/memory/gpts/gpts_memory.py
  dbgpt/agent/core/plan/awel/team_awel_layout.py
  dbgpt/agent/core/plan/planner_agent.py
  dbgpt/agent/core/user_proxy_agent.py
  dbgpt/serve/agent/agents/controller.py
  dbgpt/serve/agent/agents/expand/app_start_assisant_agent.py
  dbgpt/serve/agent/db/gpts_app.py
Labels: enhancement, agent

#2235 feat(agent):fix agent overrid bug
  dbgpt/serve/agent/agents/expand/app_start_assisant_agent.py
Labels: enhancement, agent

#2257 feat(model): Support Gitee models
  dbgpt/_private/config.py
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/proxy_adapter.py
  dbgpt/model/proxy/__init__.py
  dbgpt/model/proxy/llms/gitee.py
Labels: enhancement, model
