Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-11, with the labels that each got.

#2091 feat: Enhance the triplets extraction in the knowledge graph by the batch size
  .env.template
  dbgpt/rag/transformer/base.py
  dbgpt/rag/transformer/graph_extractor.py
  dbgpt/rag/transformer/llm_extractor.py
  dbgpt/rag/transformer/triplet_extractor.py
  dbgpt/storage/graph_store/base.py
  dbgpt/storage/graph_store/tugraph_store.py
  dbgpt/storage/knowledge_graph/community/tugraph_store_adapter.py
  dbgpt/storage/knowledge_graph/community_summary.py
  docs/docs/cookbook/rag/graph_rag_app_develop.md
Labels: enhancement, hacktoberfest

#2120 feat: add libro web
  dbgpt/app/jupyter_server_config.py
  web/package-lock.json
  web/pages/construct/flow/index.tsx
  web/pages/construct/flow/libro/index.tsx
  web/types/flow.ts
  web/yarn.lock
Labels: enhancement

#2119 feat(runtime): Execute codes in a sandbox environment
  dbgpt/agent/core/memory/gpts/gpts_memory.py
  dbgpt/app/component_configs.py
  dbgpt/app/operators/code.py
  dbgpt/app/operators/converter.py
  dbgpt/app/scene/base_chat.py
  dbgpt/core/awel/flow/base.py
  dbgpt/util/code/__init__.py
  dbgpt/util/code/server.py
  docs/static/img/application/awel/awel_flow_page.png
  docs/static/img/application/awel/flow_def_rag_ko_1.png
  docs/static/img/application/awel/flow_dev_empty_page_img.png
  docs/static/img/application/awel/flow_dev_rag_ko_2.png
  docs/static/img/application/awel/flow_dev_rag_llm_1.png
  docs/static/img/application/awel/flow_dev_rag_llm_2_.png
  docs/static/img/application/awel/flow_dev_rag_llm_3.png
  docs/static/img/application/awel/flow_dev_rag_output_1.png
  docs/static/img/application/awel/flow_dev_rag_prompt_1.png
  docs/static/img/application/awel/flow_dev_rag_save_1.png
  docs/static/img/application/awel/flow_dev_rag_show_1.png
  examples/agents/sandbox_code_agent_example.py
  examples/awel/awel_flow_ui_components.py
  setup.py
Labels: enhancement

#2124 chore: wechat update
  assets/wechat.jpg
Labels: internal

#2131 fix(milvus): Fix milvus store search with topk always set to 4
  dbgpt/storage/vector_store/milvus_store.py
Labels: fix

#2129 fix:core agent dependent prompt service bug
  dbgpt/agent/core/plan/awel/agent_operator.py
  dbgpt/agent/core/plan/awel/agent_operator_resource.py
Labels: fix

#2128 feat(web): set language and themes of libro & update csp for libro iframe
  dbgpt/serve/libro/service/jupyter_server_config.py
  web/pages/construct/flow/libro/index.tsx
Labels: enhancement, web

#2137 fix the issue that lost prev observation memory in toolExpert bug (#2136)
  dbgpt/agent/core/profile/base.py
Labels: fix

#2121 feat: call xunfei spark with stream, and fix the temperature bug
  .env.template
  .pre-commit-config.yaml
  dbgpt/_private/config.py
  dbgpt/agent/core/plan/awel/agent_operator.py
  dbgpt/agent/core/plan/awel/agent_operator_resource.py
  dbgpt/app/knowledge/api.py
  dbgpt/app/scene/base_chat.py
  dbgpt/model/proxy/llms/spark.py
  dbgpt/storage/vector_store/milvus_store.py
Labels: enhancement

#2139 feat(model): Support Qwen2.5 coder models
  dbgpt/configs/model_config.py
Labels: enhancement, model

#2146 feat(web): use the same targetOrigin
  web/pages/construct/flow/libro/index.tsx
Labels: enhancement, web

#2147 feat(ChatKnowledge):pdf loader support table extraction
  dbgpt/rag/knowledge/pdf.py
  dbgpt/rag/knowledge/tests/test_pdf.py
  dbgpt/rag/text_splitter/text_splitter.py
Labels: enhancement, ChatKnowledge

#2149 feat(web): distinguish awel flow on the ui
  web/pages/construct/flow/index.tsx
  web/public/pictures/libro.png
Labels: enhancement, web

#2148 chore:v0.6.2 tag
  README.ja.md
  README.md
  assets/wechat.jpg
  dbgpt/_version.py
  dbgpt/rag/knowledge/pdf.py
  setup.py
Labels: internal

#2155 feat(model): Support claude proxy models
  dbgpt/_private/config.py
  dbgpt/core/interface/llm.py
  dbgpt/model/adapter/proxy_adapter.py
  dbgpt/model/cluster/manager_base.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/model/proxy/__init__.py
  dbgpt/model/proxy/base.py
  dbgpt/model/proxy/llms/chatgpt.py
  dbgpt/model/proxy/llms/claude.py
  dbgpt/model/proxy/llms/deepseek.py
  dbgpt/model/proxy/llms/gemini.py
  dbgpt/model/proxy/llms/moonshot.py
  dbgpt/model/proxy/llms/ollama.py
  dbgpt/model/proxy/llms/proxy_model.py
  dbgpt/model/proxy/llms/spark.py
  dbgpt/model/proxy/llms/tongyi.py
  dbgpt/model/proxy/llms/wenxin.py
  dbgpt/model/proxy/llms/yi.py
  dbgpt/model/proxy/llms/zhipu.py
  setup.py
Labels: enhancement, model

#2157 feat(model): Support siliconflow models
  dbgpt/_private/config.py
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/proxy_adapter.py
  dbgpt/model/proxy/__init__.py
  dbgpt/model/proxy/llms/siliconflow.py
Labels: enhancement, model
