Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-03, with the labels that each got.

#1225 fix(core): Fix HTTP Trigger parse parameter bug
  dbgpt/core/awel/trigger/http_trigger.py
Labels: fix, core

#1228 fix: typo error fix
  dbgpt/_private/config.py
  dbgpt/agent/actions/chart_action.py
  dbgpt/agent/actions/code_action.py
  dbgpt/agent/actions/dashboard_action.py
  dbgpt/agent/actions/indicator_action.py
  dbgpt/agent/actions/plugin_action.py
  dbgpt/agent/agents/expand/dashboard_assistant_agent.py
  dbgpt/agent/agents/expand/retrieve_summary_assistant_agent.py
  dbgpt/agent/memory/gpts_memory.py
  dbgpt/agent/plugin/commands/built_in/audio_text.py
  dbgpt/agent/plugin/commands/built_in/display_type/__init__.py
  dbgpt/agent/plugin/commands/built_in/display_type/show_chart_gen.py
  dbgpt/agent/plugin/commands/built_in/display_type/show_table_gen.py
  dbgpt/agent/plugin/commands/built_in/display_type/show_text_gen.py
  dbgpt/agent/plugin/commands/built_in/image_gen.py
  dbgpt/agent/plugin/commands/command_manage.py
  dbgpt/agent/resource/resource_plugin_api.py
  dbgpt/app/base.py
  dbgpt/app/dbgpt_server.py
  dbgpt/app/scene/chat_agent/chat.py
  dbgpt/app/scene/chat_data/chat_excel/excel_analyze/chat.py
  dbgpt/app/scene/chat_data/chat_excel/excel_analyze/prompt.py
  dbgpt/app/scene/chat_db/auto_execute/chat.py
  dbgpt/serve/agent/team/plan/plan_action.py
  dbgpt/vis/base.py
Labels: fix

#1233 perf(rag): Support load large document
  .env.template
  dbgpt/_private/config.py
  dbgpt/app/knowledge/service.py
  dbgpt/app/scene/chat_knowledge/v1/chat.py
  dbgpt/configs/model_config.py
  dbgpt/model/__init__.py
  dbgpt/model/cluster/client.py
  dbgpt/rag/retriever/embedding.py
  dbgpt/rag/text_splitter/text_splitter.py
  dbgpt/serve/rag/assembler/base.py
  dbgpt/storage/vector_store/base.py
  dbgpt/storage/vector_store/connector.py
  dbgpt/util/tracer/base.py
Labels: performance

#1237 fix: scheduler shutdown
  dbgpt/app/initialization/scheduler.py
Labels: fix

#1238 docs: add new feature docs reference
  README.md
  README.zh.md
Labels: documentation

#1245 docs: New AWEL tutorial
  dbgpt/core/awel/__init__.py
  dbgpt/core/awel/base.py
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/operators/common_operator.py
  dbgpt/core/awel/task/base.py
  dbgpt/core/awel/task/task_impl.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/core/awel/trigger/trigger_manager.py
  dbgpt/model/proxy/__init__.py
  docs/docs/awel/awel_tutorial/advanced_guide/4.1_lifecycle.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.1_map_operator.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.2_reduce_operator.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.3_join_operator.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.4_branch_operator.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.5_streamify_operator.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.6_unstreamify_operator.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.7_transform_stream_operator.md
  docs/docs/awel/awel_tutorial/basic_syntax/2.8_input_operator.md
  docs/docs/awel/awel_tutorial/getting_started/1.1_hello_world.md
  docs/docs/awel/awel_tutorial/getting_started/1.2_how_works.md
  docs/docs/awel/awel_tutorial/getting_started/1.3_custom_operator.md
  docs/docs/awel/awel_tutorial/network_program/3.1_http_trigger.md
  docs/docs/awel/awel_tutorial/network_program/3.2_http_trigger_get.md
  docs/docs/awel/awel_tutorial/network_program/3.3_http_trigger_post.md
  docs/docs/awel/awel_tutorial/network_program/3.4_http_trigger_streaming.md
  docs/docs/awel/cookbook/multi_round_chat_withllm.md
  docs/docs/awel/cookbook/quickstart_basic_awel_workflow.md
  docs/docs/awel/how_to/operator/join.md
  docs/docs/awel/how_to/operator/map.md
  docs/docs/awel/how_to/operator/reduce.md
  docs/docs/awel/how_to/operator/streamify_abs_operator.md
  docs/docs/awel/how_to/operator/trigger.md
  docs/docs/awel/how_to/workflow/dag_pipeline.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/sidebars.js
  docs/static/img/awel/awel_tutorial/branch_operator_example_1.png
  docs/static/img/awel/awel_tutorial/first_hello_world_two_tasks.png
  docs/static/img/awel/awel_tutorial/join_operator_example_1.png
  docs/yarn.lock
Labels: documentation

#1251 feat: AWEL flow supports dynamic parameters
  dbgpt/app/scene/chat_knowledge/v1/chat.py
  dbgpt/core/awel/flow/__init__.py
  dbgpt/core/awel/flow/base.py
  dbgpt/core/awel/util/parameter_util.py
  dbgpt/serve/agent/team/layout/agent_operator_resource.py
  dbgpt/serve/rag/operators/knowledge_space.py
Labels: enhancement

#1250 fix: fix knowledge_space_dao.update_knowledge_space call in Knowledge…
  dbgpt/app/knowledge/service.py
Labels: fix

#1256 feat: APIServer supports embeddings
  dbgpt/model/cluster/apiserver/api.py
  dbgpt/model/parameter.py
  dbgpt/rag/embedding/__init__.py
  dbgpt/rag/embedding/embeddings.py
  dbgpt/storage/vector_store/base.py
  dbgpt/storage/vector_store/connector.py
  docs/docs/installation/advanced_usage/OpenAI_SDK_call.md
  examples/rag/embedding_rag_example.py
  examples/rag/rag_embedding_api_example.py
Labels: enhancement

#1261 chore:update wechat
  assets/wechat.jpg
Labels: internal

#1263 docs: overview update & fix reference addr
  README.md
  docs/docs/awel/awel.md
  docs/docs/overview.md
Labels: documentation

#1246 feat(model): Add support for multiple versions of the same model
  dbgpt/model/cluster/worker/manager.py
  dbgpt/model/parameter.py
Labels: enhancement, model

#1286 chore:upgrade wechat
  assets/wechat.jpg
  dbgpt/agent/agents/expand/plugin_assistant_agent.py
  dbgpt/rag/knowledge/url.py
Labels: internal

#1283 fix(agent): Fix agent loss message bug
  dbgpt/agent/actions/plugin_action.py
  dbgpt/agent/agents/agent_new.py
  dbgpt/agent/agents/base_agent_new.py
  dbgpt/agent/memory/gpts_memory.py
  dbgpt/agent/resource/resource_api.py
  dbgpt/serve/agent/agents/controller.py
  dbgpt/serve/agent/resource_loader/plugin_hub_load_client.py
  dbgpt/serve/agent/team/layout/agent_operator.py
  dbgpt/serve/agent/team/layout/team_awel_layout_new.py
  dbgpt/serve/agent/team/plan/team_auto_plan.py
Labels: fix, agent

#1298 chore: Add pylint for storage
  .mypy.ini
  Makefile
  assets/schema/dbgpt.sql
  dbgpt/app/openapi/api_v1/editor/_chat_history/__init__.py
  dbgpt/app/openapi/api_v1/editor/_chat_history/base.py
  dbgpt/app/openapi/api_v1/editor/_chat_history/chat_hisotry_factory.py
  dbgpt/app/openapi/api_v1/editor/_chat_history/meta_db_history.py
  dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
  dbgpt/app/scene/operators/app_operator.py
  dbgpt/core/awel/trigger/iterator_trigger.py
  dbgpt/model/cluster/embedding/loader.py
  dbgpt/model/cluster/embedding/remote_embedding.py
  dbgpt/model/cluster/worker/embedding_worker.py
  dbgpt/rag/chunk_manager.py
  dbgpt/serve/flow/service/service.py
  dbgpt/storage/__init__.py
  dbgpt/storage/cache/__init__.py
  dbgpt/storage/cache/embedding_cache.py
  dbgpt/storage/cache/llm_cache.py
  dbgpt/storage/cache/manager.py
  dbgpt/storage/cache/operators.py
  dbgpt/storage/cache/protocal/__init__.py
  dbgpt/storage/cache/protocol/__init__.py
  dbgpt/storage/cache/storage/__init__.py
  dbgpt/storage/cache/storage/base.py
  dbgpt/storage/cache/storage/disk/__init__.py
  dbgpt/storage/cache/storage/disk/disk_storage.py
  dbgpt/storage/cache/storage/tests/test_storage.py
  dbgpt/storage/chat_history/__init__.py
  dbgpt/storage/chat_history/chat_history_db.py
  dbgpt/storage/chat_history/storage_adapter.py
  dbgpt/storage/chat_history/store_type/__init__.py
  dbgpt/storage/chat_history/store_type/duckdb_history.py
  dbgpt/storage/chat_history/store_type/file_history.py
  dbgpt/storage/chat_history/store_type/mem_history.py
  dbgpt/storage/metadata/__init__.py
  dbgpt/storage/metadata/_base_dao.py
  dbgpt/storage/metadata/db_factory.py
  dbgpt/storage/metadata/db_manager.py
  dbgpt/storage/metadata/db_storage.py
  dbgpt/storage/metadata/meta_data.py
  dbgpt/storage/schema.py
  dbgpt/storage/vector_store/__init__.py
  dbgpt/storage/vector_store/base.py
  dbgpt/storage/vector_store/chroma_store.py
  dbgpt/storage/vector_store/connector.py
  dbgpt/storage/vector_store/milvus_store.py
  dbgpt/storage/vector_store/pgvector_store.py
  dbgpt/storage/vector_store/weaviate_store.py
  requirements/lint-requirements.txt
Labels: internal

#1308 fix(datasource): Fix the bug of doris missing comments
  dbgpt/datasource/rdbms/conn_doris.py
Labels: fix

#1311 fix(awel): Fix awel check empty data bug
  dbgpt/core/awel/task/base.py
  dbgpt/core/awel/task/task_impl.py
Labels: fix

#1325 fix: Fix build docker image error
  docker/base/Dockerfile
  setup.py
Labels: fix

#1332 fix: pg py dependency problem
  setup.py
Labels: fix

#1341 feat: Run AWEL flow in CLI
  dbgpt/app/openapi/api_v1/api_v1.py
  dbgpt/app/openapi/api_v2.py
  dbgpt/cli/cli_scripts.py
  dbgpt/client/_cli.py
  dbgpt/client/client.py
  dbgpt/client/flow.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/trigger/iterator_trigger.py
  dbgpt/core/interface/llm.py
  dbgpt/core/interface/operators/llm_operator.py
  dbgpt/core/schema/api.py
  dbgpt/model/utils/chatgpt_utils.py
  dbgpt/serve/flow/api/endpoints.py
  dbgpt/serve/flow/service/service.py
  dbgpt/util/console/__init__.py
  dbgpt/util/console/console.py
  dbgpt/util/dbgpts/cli.py
  dbgpt/util/dbgpts/loader.py
  dbgpt/util/dbgpts/repo.py
  i18n/Makefile
  i18n/locales/fr/LC_MESSAGES/dbgpt_client.mo
  i18n/locales/fr/LC_MESSAGES/dbgpt_client.po
  i18n/locales/fr/LC_MESSAGES/dbgpt_model.mo
  i18n/locales/fr/LC_MESSAGES/dbgpt_model.po
  i18n/locales/ja/LC_MESSAGES/dbgpt_client.mo
  i18n/locales/ja/LC_MESSAGES/dbgpt_client.po
  i18n/locales/ja/LC_MESSAGES/dbgpt_model.mo
  i18n/locales/ja/LC_MESSAGES/dbgpt_model.po
  i18n/locales/ko/LC_MESSAGES/dbgpt_client.mo
  i18n/locales/ko/LC_MESSAGES/dbgpt_client.po
  i18n/locales/ko/LC_MESSAGES/dbgpt_model.mo
  i18n/locales/ko/LC_MESSAGES/dbgpt_model.po
  i18n/locales/ru/LC_MESSAGES/dbgpt_client.mo
  i18n/locales/ru/LC_MESSAGES/dbgpt_client.po
  i18n/locales/ru/LC_MESSAGES/dbgpt_model.mo
  i18n/locales/ru/LC_MESSAGES/dbgpt_model.po
  i18n/locales/zh_CN/LC_MESSAGES/dbgpt_client.mo
  i18n/locales/zh_CN/LC_MESSAGES/dbgpt_client.po
  i18n/locales/zh_CN/LC_MESSAGES/dbgpt_model.mo
  i18n/locales/zh_CN/LC_MESSAGES/dbgpt_model.po
  i18n/translate_util.py
  setup.py
Labels: enhancement

#1345 docs: Add AWEL chat data cookbook
  dbgpt/datasource/operators/__init__.py
  dbgpt/rag/operators/db_schema.py
  docs/docs/awel/cookbook/write_your_chat_database.md
  docs/sidebars.js
  docs/static/img/awel/cookbook/chat_data_chat_data_dag.png
  docs/static/img/awel/cookbook/chat_data_load_schema_dag.png
  examples/sdk/chat_data_with_awel.py
Labels: documentation

#1343 feat: Client support chatdata
  dbgpt/app/initialization/serve_initialization.py
  dbgpt/app/openapi/api_v2.py
  dbgpt/client/datasource.py
  dbgpt/client/schema.py
  dbgpt/datasource/manages/connect_config_db.py
  dbgpt/serve/datasource/api/__init__.py
  dbgpt/serve/datasource/api/endpoints.py
  dbgpt/serve/datasource/api/schemas.py
  dbgpt/serve/datasource/config.py
  dbgpt/serve/datasource/dependencies.py
  dbgpt/serve/datasource/models/__init__.py
  dbgpt/serve/datasource/models/models.py
  dbgpt/serve/datasource/serve.py
  dbgpt/serve/datasource/service/__init__.py
  dbgpt/serve/datasource/service/service.py
  dbgpt/serve/datasource/tests/__init__.py
  docs/docs/api/app.md
  docs/docs/api/datasource.md
  docs/docs/api/flow.md
  docs/sidebars.js
  examples/client/datasource_crud_example.py
Labels: enhancement

#1346 chore:version and wechat update
  assets/wechat.jpg
  dbgpt/_version.py
  setup.py
Labels: internal

#1350 feat(model): Support Starling-LM-7B-beta
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
  setup.py
Labels: enhancement, model

#1351 fix: Fix the issue of invalid port settings
  dbgpt/_private/config.py
  dbgpt/app/base.py
  dbgpt/app/dbgpt_server.py
Labels: fix
