Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-10, with the labels that each got.

#2048 chore:wechat update
  assets/wechat.jpg
Labels: internal

#2051 fix: Fix long message response error
  assets/schema/dbgpt.sql
Labels: fix

#2077 feat(model): Passing stop parameter to proxyllm
  dbgpt/core/interface/llm.py
  dbgpt/model/cluster/apiserver/api.py
  dbgpt/model/cluster/base.py
  dbgpt/model/parameter.py
  dbgpt/model/proxy/llms/chatgpt.py
  dbgpt/model/proxy/llms/deepseek.py
  dbgpt/model/proxy/llms/gemini.py
  dbgpt/model/proxy/llms/moonshot.py
  dbgpt/model/proxy/llms/spark.py
  dbgpt/model/proxy/llms/tongyi.py
  dbgpt/model/proxy/llms/yi.py
  dbgpt/model/proxy/llms/zhipu.py
  dbgpt/rag/knowledge/docx.py
Labels: enhancement, model, hacktoberfest

#2074 Update OceanBaseStore to be compatible with oceanbase-4.3.3.0
  dbgpt/_private/config.py
  dbgpt/storage/vector_store/oceanbase_store.py
  docker/compose_examples/dbgpt-oceanbase-docker-compose.yml
  docs/docs/application/advanced_tutorial/rag.md
  docs/docs/faq/kbqa.md
Labels: hacktoberfest

#2072 fix: replace deprecated method and add missing decorator
  dbgpt/agent/core/action/base.py
  dbgpt/agent/core/memory/gpts/default_gpts_memory.py
  dbgpt/agent/core/plan/awel/agent_operator_resource.py
Labels: fix

#2070 feat: add evaluation service module for RAG and Agent
  assets/schema/dbgpt.sql
  dbgpt/app/initialization/serve_initialization.py
  dbgpt/app/knowledge/api.py
  dbgpt/client/evaluation.py
  dbgpt/core/interface/evaluation.py
  dbgpt/rag/evaluation/answer.py
  dbgpt/rag/index/base.py
  dbgpt/rag/operators/evaluation.py
  dbgpt/rag/retriever/embedding.py
  dbgpt/serve/agent/agents/controller.py
  dbgpt/serve/agent/evaluation/evaluation.py
  dbgpt/serve/agent/evaluation/evaluation_metric.py
  dbgpt/serve/evaluate/__init__.py
  dbgpt/serve/evaluate/api/__init__.py
  dbgpt/serve/evaluate/api/endpoints.py
  dbgpt/serve/evaluate/api/schemas.py
  dbgpt/serve/evaluate/config.py
  dbgpt/serve/evaluate/dependencies.py
  dbgpt/serve/evaluate/models/__init__.py
  dbgpt/serve/evaluate/models/models.py
  dbgpt/serve/evaluate/models/models_dataset.py
  dbgpt/serve/evaluate/serve.py
  dbgpt/serve/evaluate/service/__init__.py
  dbgpt/serve/evaluate/service/service.py
  dbgpt/serve/rag/operators/knowledge_space.py
  dbgpt/serve/rag/service/service.py
  docs/docs/api/evaluation.md
  docs/sidebars.js
  examples/client/client_evaluation.py
Labels: enhancement, hacktoberfest

#2033 feat: add document structure into GraphRAG
  .env.template
  dbgpt/_private/config.py
  dbgpt/app/knowledge/service.py
  dbgpt/datasource/conn_tugraph.py
  dbgpt/rag/transformer/graph_extractor.py
  dbgpt/rag/transformer/keyword_extractor.py
  dbgpt/serve/rag/connector.py
  dbgpt/storage/graph_store/base.py
  dbgpt/storage/graph_store/factory.py
  dbgpt/storage/graph_store/graph.py
  dbgpt/storage/graph_store/memgraph_store.py
  dbgpt/storage/graph_store/tugraph_store.py
  dbgpt/storage/knowledge_graph/base.py
  dbgpt/storage/knowledge_graph/community/base.py
  dbgpt/storage/knowledge_graph/community/community_store.py
  dbgpt/storage/knowledge_graph/community/factory.py
  dbgpt/storage/knowledge_graph/community/memgraph_store_adapter.py
  dbgpt/storage/knowledge_graph/community/tugraph_adapter.py
  dbgpt/storage/knowledge_graph/community/tugraph_store_adapter.py
  dbgpt/storage/knowledge_graph/community_summary.py
  dbgpt/storage/knowledge_graph/knowledge_graph.py
  dbgpt/storage/metadata/db_manager.py
  docs/docs/cookbook/rag/graph_rag_app_develop.md
  docs/docs/cookbook/rag/image_graphrag_0_6_1.png
  docs/static/img/chat_knowledge/graph_rag/image_graphrag_0_6_1.png
  tests/intetration_tests/datasource/test_conn_tugraph.py
  tests/intetration_tests/graph_store/test_memgraph_store.py
  tests/intetration_tests/graph_store/test_tugraph_store.py
  tests/intetration_tests/graph_store/test_tugraph_store_with_summary.py
Labels: enhancement, GraphRAG, hacktoberfest

#2081 docs: app & agents development document
  README.md
  README.zh.md
  assets/wechat.jpg
  dbgpt/serve/agent/agents/expand/app_start_assisant_agent.py
  docs/docs/cookbook/app/data_analysis_app_develop.md
  docs/docs/tutorials/index.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/static/img/cookbook/app_code.png
  docs/static/img/cookbook/app_create_with_agent.png
  docs/static/img/cookbook/app_intent_knowledge.png
  docs/static/img/cookbook/awel_db_expert.png
  docs/static/img/cookbook/awel_expert_v1.png
  docs/static/img/cookbook/awel_web_search.png
  docs/static/img/cookbook/awel_web_search_tool.png
  docs/static/img/cookbook/chunk_sep.png
  docs/static/img/cookbook/data_app_awel.png
  docs/static/img/cookbook/data_app_build.png
  docs/static/img/cookbook/data_app_build_parameters.png
  docs/static/img/cookbook/data_app_chat.png
  docs/static/img/cookbook/data_app_create.png
  docs/static/img/cookbook/data_expert_chat.png
  docs/static/img/cookbook/datasource.png
  docs/static/img/cookbook/knowledge_base.png
  docs/static/img/cookbook/knowledge_base_success.png
  docs/static/img/cookbook/knowlege_base_upload.png
  docs/static/img/cookbook/qa_app_build_parameters.png
  docs/static/img/cookbook/qa_app_chat.png
  docs/static/img/cookbook/search_app.png
  docs/static/img/cookbook/search_app_build.png
  docs/static/img/cookbook/search_app_chat.png
Labels: documentation, hacktoberfest

#2083 chore:v0.6.1 version
  dbgpt/_version.py
  dbgpt/serve/evaluate/api/endpoints.py
  dbgpt/serve/evaluate/api/schemas.py
  dbgpt/serve/evaluate/models/models.py
  dbgpt/serve/evaluate/models/models_dataset.py
  dbgpt/serve/evaluate/service/service.py
  setup.py
Labels: internal

#2084 refactor: the document structure of GraphRAG
  .env.template
  dbgpt/_private/config.py
  dbgpt/core/interface/knowledge.py
  dbgpt/serve/rag/connector.py
  dbgpt/storage/graph_store/base.py
  dbgpt/storage/graph_store/graph.py
  dbgpt/storage/graph_store/memgraph_store.py
  dbgpt/storage/graph_store/tugraph_store.py
  dbgpt/storage/knowledge_graph/base.py
  dbgpt/storage/knowledge_graph/community/base.py
  dbgpt/storage/knowledge_graph/community/memgraph_store_adapter.py
  dbgpt/storage/knowledge_graph/community/tugraph_store_adapter.py
  dbgpt/storage/knowledge_graph/community_summary.py
  docs/docs/cookbook/rag/graph_rag_app_develop.md
  docs/docs/cookbook/rag/image_graphrag_0_6_1.png
Labels: internal, hacktoberfest

#2085 fix: fix unit test error
  dbgpt/datasource/conn_tugraph.py
  dbgpt/rag/summary/gdbms_db_summary.py
  dbgpt/storage/graph_store/tugraph_store.py
  dbgpt/storage/knowledge_graph/community/base.py
  dbgpt/storage/knowledge_graph/community/memgraph_store_adapter.py
  dbgpt/storage/knowledge_graph/community/tugraph_store_adapter.py
  dbgpt/storage/knowledge_graph/community_summary.py
  dbgpt/storage/knowledge_graph/knowledge_graph.py
  examples/rag/graph_rag_example.py
  tests/intetration_tests/graph_store/test_tugraph_store.py
  tests/unit_tests/graph/test_graph.py
Labels: fix, GraphRAG, hacktoberfest

#2086 fix: GRAPH_COMMUNITY_SUMMARY_ENABLED = False error.
  dbgpt/rag/index/base.py
  dbgpt/storage/knowledge_graph/community_summary.py
  examples/rag/graph_rag_example.py
Labels: fix, hacktoberfest

#2100 os environment variables should take precedences over the defaults, f…
  dbgpt/storage/vector_store/elastic_store.py
Labels: hacktoberfest

#2095 fix:excel_reader.py unicode bug
  dbgpt/app/scene/chat_data/chat_excel/excel_reader.py
Labels: fix

#2107 docs(core): Add AWEL shared slides
  docs/docs/awel/awel_tutorial/AWEL-10-29.ipynb
Labels: documentation, core

#2111 chore: wechat update
  assets/wechat.jpg
Labels: internal, hacktoberfest, hacktoberfest-accepted
