Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-02, with the labels that each got.

#1141 fix when add api_azure_deployment keyword ,openAI can not run
  dbgpt/model/utils/chatgpt_utils.py
Labels: fix

#1137 feat(model): Add support for Azure openAI
  dbgpt/model/utils/chatgpt_utils.py
  docs/docs/installation/advanced_usage/More_proxyllms.md
  docs/sidebars.js
Labels: enhancement, model

#1149 chore: update charts display
  README.md
  README.zh.md
  assets/wechat.jpg
Labels: internal

#1162 docs: update description and dbgpts
  README.md
  README.zh.md
  assets/wechat.jpg
Labels: documentation

#1174 feat:add rag awel operator view metadata.
  dbgpt/core/awel/flow/base.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/core/interface/operators/llm_operator.py
  dbgpt/rag/operators/knowledge.py
  dbgpt/rag/operators/rewrite.py
  dbgpt/rag/operators/summary.py
  dbgpt/serve/rag/operators/knowledge_space.py
  examples/awel/simple_rag_summary_example.py
  examples/rag/simple_rag_embedding_example.py
  examples/rag/simple_rag_retriever_example.py
Labels: enhancement

#1176 docs: Add upgrade to v0.5.0 documents
  docs/docs/upgrade/v0.5.0.md
  docs/sidebars.js
Labels: documentation

#1178 chore:update wechat.jpg
  assets/wechat.jpg
Labels: internal

#1180 feat(core): Support more chat flows
  dbgpt/_version.py
  dbgpt/app/openapi/api_v1/api_v1.py
  dbgpt/core/awel/flow/base.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/operators/stream_operator.py
  dbgpt/core/interface/operators/prompt_operator.py
  dbgpt/serve/flow/service/service.py
  dbgpt/util/dbgpts/repo.py
  docs/docs/upgrade/v0.5.0.md
  setup.py
Labels: enhancement, core

#1185 feat(core): Support RAG chat flow
  dbgpt/core/awel/runner/local_runner.py
  dbgpt/serve/flow/service/service.py
  dbgpt/storage/vector_store/milvus_store.py
  dbgpt/util/dbgpts/cli.py
  dbgpt/util/dbgpts/repo.py
  dbgpt/util/function_utils.py
  docs/docs/awel/cookbook/quickstart_basic_awel_workflow.md
  scripts/setup_autodl_env.sh
  setup.py
Labels: enhancement, core

#1187 feat(model): Support gemma model
  README.md
  README.zh.md
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1198 docs: update comments for gender and pay_status fields in test_case_m…
  docker/examples/dashboard/test_case_mysql_data.py
Labels: documentation

#1211 feat(core): Dynamically loading dbgpts
  dbgpt/app/component_configs.py
  dbgpt/app/initialization/scheduler.py
  dbgpt/cli/cli_scripts.py
  dbgpt/core/awel/dag/loader.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/model/base.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/serve/flow/config.py
  dbgpt/serve/flow/service/service.py
  dbgpt/util/dbgpts/base.py
  dbgpt/util/dbgpts/cli.py
  dbgpt/util/dbgpts/loader.py
  dbgpt/util/dbgpts/repo.py
  dbgpt/util/dbgpts/template.py
  setup.py
Labels: enhancement, core

#1216 docs: add docs and usage for v0.5.0
  assets/wechat.jpg
  docs/docs/application/app_usage.md
  docs/docs/application/awel_flow_usage.md
  docs/docs/changelog/Released_V0.5.0.md
  docs/docs/cookbook/agents/codeagent_develop.md
  docs/docs/cookbook/app/data_analysis_app_develop.md
  docs/sidebars.js
  docs/static/img/app/app_agent_reporter.jpg
  docs/static/img/app/app_agents.png
  docs/static/img/app/app_analysis.png
  docs/static/img/app/app_analysis_black.png
  docs/static/img/app/app_awel.png
  docs/static/img/app/app_list.png
  docs/static/img/app/app_search.png
  docs/static/img/app/awel_flow_list.png
  docs/static/img/app/awel_flow_node.png
  docs/static/img/app/awel_flow_node_plus.png
  docs/static/img/app/dbgpts_app_install.png
  docs/static/img/app/dbgpts_apps.png
  docs/static/img/app/dbgpts_cli.png
  docs/static/img/app/dbgpts_flow_black.png
  docs/static/img/app/flow_detail.png
Labels: documentation
