Repository eosphoros-ai/DB-GPT, pull requests merged in 2024-07, with the labels that each got.

#1687 fix(core): Fix write log files bug
  dbgpt/util/utils.py
Labels: fix, core

#1690 feat(core): Support opentelemetry exporter
  .env.template
  dbgpt/agent/core/base_agent.py
  dbgpt/app/base.py
  dbgpt/app/dbgpt_server.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/runner/local_runner.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/model/base.py
  dbgpt/model/cluster/apiserver/api.py
  dbgpt/model/cluster/apiserver/tests/test_api.py
  dbgpt/model/cluster/controller/controller.py
  dbgpt/model/cluster/worker/default_worker.py
  dbgpt/model/cluster/worker/manager.py
  dbgpt/model/cluster/worker/remote_worker.py
  dbgpt/model/parameter.py
  dbgpt/rag/embedding/embeddings.py
  dbgpt/rag/embedding/rerank.py
  dbgpt/rag/retriever/db_schema.py
  dbgpt/rag/retriever/embedding.py
  dbgpt/rag/retriever/rerank.py
  dbgpt/serve/agent/agents/controller.py
  dbgpt/util/executor_utils.py
  dbgpt/util/parameter_utils.py
  dbgpt/util/tracer/__init__.py
  dbgpt/util/tracer/base.py
  dbgpt/util/tracer/opentelemetry.py
  dbgpt/util/tracer/tracer_cli.py
  dbgpt/util/tracer/tracer_impl.py
  dbgpt/util/tracer/tracer_middleware.py
  docker/compose_examples/observability/docker-compose.yml
  docs/docs/application/advanced_tutorial/debugging.md
  docs/docs/application/advanced_tutorial/observability.md
  docs/sidebars.js
  docs/static/img/application/advanced_tutorial/observability_img1.png
  docs/static/img/application/advanced_tutorial/observability_img2.png
  docs/static/img/application/advanced_tutorial/observability_img3.png
  docs/static/img/application/advanced_tutorial/observability_img4.png
  docs/static/img/application/advanced_tutorial/observability_img5.png
  setup.py
Labels: enhancement, core

#1706 fix: FIx GraphRAG build error
  dbgpt/rag/index/base.py
  dbgpt/rag/retriever/embedding.py
Labels: fix

#1717 chore:update wechat
  assets/wechat.jpg
Labels: internal

#1710 fix: Fix http empty headers error
  dbgpt/model/cluster/worker/remote_worker.py
  dbgpt/rag/embedding/embeddings.py
  dbgpt/rag/embedding/rerank.py
Labels: fix

#1720 feat(model): Support codegeex4-all-9b
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1719 fix(model): Stream object can't use await
  dbgpt/rag/knowledge/url.py
Labels: fix, model

#1732 fix(chat knowledge): add missing context property
  dbgpt/serve/rag/models/models.py
Labels: fix

#1697 fix(web): fix line chart using interval field as xAxis & fix pie chart tooltip
  web/components/chart/autoChart/charts/multi-line-chart.ts
  web/components/chart/autoChart/charts/multi-measure-line-chart.ts
  web/components/chart/autoChart/charts/util.ts
  web/components/chart/autoChart/index.tsx
Labels: fix, web

#1735 feat(model): Support internlm2.5 models
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
Labels: enhancement, model

#1734 feat(core): Multiple ways to run dbgpts
  dbgpt/cli/cli_scripts.py
  dbgpt/client/_cli.py
  dbgpt/client/client.py
  dbgpt/client/flow.py
  dbgpt/core/awel/dag/base.py
  dbgpt/core/awel/dag/dag_manager.py
  dbgpt/core/awel/flow/flow_factory.py
  dbgpt/core/awel/operators/base.py
  dbgpt/core/awel/trigger/base.py
  dbgpt/core/awel/trigger/http_trigger.py
  dbgpt/core/awel/trigger/trigger_manager.py
  dbgpt/core/awel/util/chat_util.py
  dbgpt/serve/flow/service/service.py
  dbgpt/util/dbgpts/loader.py
  docs/docs/dbgpts/introduction.md
  docs/sidebars.js
  docs/static/img/dbgpts/awel_flow_simple_streaming_chat_1.png
  docs/static/img/dbgpts/awel_flow_simple_streaming_chat_2.png
  examples/awel/simple_chat_dag_example.py
Labels: enhancement, core

#1741 docs: Multi-version document build
  .dockerignore
  .github/workflows/doc-image-publish.yml
  docs/Dockerfile-deploy
  docs/README.md
  docs/docs/agents/introduction/tools.md
  docs/docs/api/knowledge.md
  docs/docs/application/advanced_tutorial/api.md
  docs/docs/application/advanced_tutorial/cli.md
  docs/docs/application/advanced_tutorial/smmf.md
  docs/docs/application/started_tutorial/chat_dashboard.md
  docs/docs/awel/cookbook/first_rag_with_awel.md
  docs/docs/awel/cookbook/write_your_chat_database.md
  docs/docs/installation/advanced_usage/OpenAI_SDK_call.md
  docs/docs/installation/model_service/cluster_ha.md
  docs/docs/installation/sourcecode.md
  docs/docs/overview.md
  docs/docs/quickstart.md
  docs/docusaurus.config.js
  docs/nginx/nginx-docs-ssl.conf
  docs/nginx/nginx-docs.conf
  docs/package-lock.json
  docs/package.json
  docs/versions.json
  docs/yarn.lock
Labels: documentation

#1744 feat(model): Support llama3.1 models
  README.ja.md
  README.md
  README.zh.md
  dbgpt/agent/expand/resources/search_tool.py
  dbgpt/configs/model_config.py
  dbgpt/model/adapter/hf_adapter.py
  docs/blog/2024-07-24-db-gpt-llama-3.1-support.md
  docs/blog/authors.yml
  docs/blog/tags.yml
  docs/docusaurus.config.js
Labels: enhancement, model

#1747 chore:wechat update
  assets/wechat.jpg
Labels: internal

#1753 fix(ChatKnowledge): Fix chat knowledge error
  dbgpt/app/openapi/api_v1/api_v1.py
  requirements/dev-requirements.txt
Labels: fix, ChatKnowledge

#1755 fix(rag): Fix db schema aretriever bug
  .github/workflows/sync-docs.yaml
  dbgpt/rag/retriever/db_schema.py
  dbgpt/rag/retriever/tests/test_db_struct.py
Labels: fix
