Repository eosphoros-ai/DB-GPT, pull requests merged in 2025-05, with the labels that each got.

#2669 feat(RAG):add tree retriever based on document directory level
  examples/rag/doc_tree_retriever_example.py
  packages/dbgpt-core/src/dbgpt/core/interface/knowledge.py
  packages/dbgpt-core/src/dbgpt/rag/knowledge/base.py
  packages/dbgpt-core/src/dbgpt/storage/base.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/knowledge/markdown.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/retriever/doc_tree.py
Labels: enhancement

#2676 feat(model): Add patch for Qwen3 moe
  packages/dbgpt-core/src/dbgpt/core/interface/llm.py
  packages/dbgpt-core/src/dbgpt/model/adapter/base.py
  packages/dbgpt-core/src/dbgpt/model/adapter/hf_adapter.py
  packages/dbgpt-core/src/dbgpt/model/adapter/loader.py
  packages/dbgpt-core/src/dbgpt/model/cluster/worker/default_worker.py
  packages/dbgpt-core/src/dbgpt/model/llm/llm_out/hf_chat_llm.py
  packages/dbgpt-core/src/dbgpt/model/llm/llm_out/vllm_llm.py
  packages/dbgpt-core/src/dbgpt/model/llm/monkey_patch.py
  packages/dbgpt-core/src/dbgpt/model/utils/hf_stream_utils.py
  packages/dbgpt-core/src/dbgpt/model/utils/llm_metrics.py
Labels: enhancement, model

#2690 feat(model): Support llama.cpp for GLM4-z1
  packages/dbgpt-core/pyproject.toml
Labels: enhancement, model

#2686 fix: issue 2685
  web/components/knowledge/doc-upload-form.tsx
Labels: fix

#2695 fix: resolve KeyError: 'question' in chat_dashboard prompt template
  packages/dbgpt-app/src/dbgpt_app/scene/chat_dashboard/chat.py
Labels: fix

#2696 fix: Fix typo
  packages/dbgpt-app/src/dbgpt_app/operators/datasource.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_data/chat_excel/excel_analyze/prompt.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_db/auto_execute/prompt.py
Labels: fix

#2701 docs(datasource): integration oracle doc
  docs/docs/installation/integrations.md
  docs/docs/installation/integrations/clickhouse_install.md
  docs/docs/installation/integrations/duckdb_install.md
  docs/docs/installation/integrations/mssql_install.md
  docs/docs/installation/integrations/oracle_install.md
  docs/docs/installation/integrations/postgres_install.md
  docs/sidebars.js
Labels: documentation

#2705 chore: upgrade pandas version
  packages/dbgpt-core/pyproject.toml
Labels: internal

#2716 feat(flow): Add Chat Data template
  packages/dbgpt-app/src/dbgpt_app/component_configs.py
  packages/dbgpt-app/src/dbgpt_app/operators/datasource.py
  packages/dbgpt-app/src/dbgpt_app/operators/report.py
  packages/dbgpt-core/src/dbgpt/util/pd_utils.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/chat-data-awel-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/chat-data-awel-flow-template.json
  tests/intetration_tests/datasource/test_conn_oracle.py
Labels: enhancement

#2724 chore(docs): Update ding group
  assets/ding.jpg
Labels: internal

#2725 fix(scene): fix chat scene config custom prompt
  packages/dbgpt-app/src/dbgpt_app/scene/base_chat.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_dashboard/chat.py
  packages/dbgpt-serve/src/dbgpt_serve/prompt/models/models.py
Labels: fix

#2717 fix: fix unit test and some code typos
  packages/dbgpt-app/src/dbgpt_app/scene/chat_data/chat_excel/excel_analyze/prompt.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_data/chat_excel/excel_learning/chat.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_knowledge/v1/prompt.py
  packages/dbgpt-core/src/dbgpt/datasource/rdbms/base.py
  packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_oracle.py
  tests/intetration_tests/datasource/test_conn_mysql.py
  tests/intetration_tests/datasource/test_conn_oracle.py
Labels: fix

#2722 feat(ChatKnowledge):add hybrid search for knowledge space.
  packages/dbgpt-core/src/dbgpt/rag/retriever/base.py
  packages/dbgpt-core/src/dbgpt/storage/base.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/retriever/doc_tree.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/api/endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/retriever/knowledge_space.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/service/service.py
Labels: enhancement, ChatKnowledge
