Repository eosphoros-ai/DB-GPT, pull requests merged in 2025-03, with the labels that each got.

#2380 fix(clickhouse): resolve clickhouse connection error
  packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_clickhouse.py
Labels: fix, cli

#2383 ci(docs): Fix build doc error
  .github/workflows/doc-image-publish.yml
  docs/Dockerfile-deploy
Labels: internal

#2386 docs: add vllm llama_cpp docs and standardize configs
  configs/dbgpt-graphrag.toml
  configs/dbgpt-local-glm.toml
  configs/dbgpt-local-llama-cpp-server.toml
  configs/dbgpt-local-llama-cpp.toml
  configs/dbgpt-local-qwen.toml
  configs/dbgpt-local-vllm.toml
  configs/dbgpt-proxy-deepseek.toml
  docs/README.md
  docs/docs/quickstart.md
Labels: documentation

#2393 fix(model): Fix reasoning output bug
  configs/dbgpt-local-glm.toml
  docs/docs/quickstart.md
  packages/dbgpt-accelerator/README.md
  packages/dbgpt-accelerator/dbgpt-acc-auto/README.md
  packages/dbgpt-accelerator/dbgpt-acc-auto/pyproject.toml
  packages/dbgpt-accelerator/dbgpt-acc-flash-attn/README.md
  packages/dbgpt-accelerator/dbgpt-acc-flash-attn/pyproject.toml
  packages/dbgpt-accelerator/src/dbgpt_accelerator/__init__.py
  packages/dbgpt-app/pyproject.toml
  packages/dbgpt-core/src/dbgpt/core/interface/parameter.py
  packages/dbgpt-core/src/dbgpt/model/adapter/base.py
  packages/dbgpt-core/src/dbgpt/model/adapter/hf_adapter.py
  packages/dbgpt-core/src/dbgpt/model/adapter/llama_cpp_adapter.py
  packages/dbgpt-core/src/dbgpt/model/adapter/loader.py
  packages/dbgpt-core/src/dbgpt/model/adapter/vllm_adapter.py
  packages/dbgpt-core/src/dbgpt/model/cluster/worker/default_worker.py
  packages/dbgpt-core/src/dbgpt/model/cluster/worker/manager.py
  packages/dbgpt-core/src/dbgpt/model/llm/llama_cpp/llama_cpp.py
  packages/dbgpt-core/src/dbgpt/model/llm/llama_cpp/llama_cpp_server.py
  packages/dbgpt-core/src/dbgpt/model/llm/llm_out/hf_chat_llm.py
  packages/dbgpt-core/src/dbgpt/model/llm/llm_out/vllm_llm.py
  packages/dbgpt-core/src/dbgpt/model/proxy/llms/ollama.py
  packages/dbgpt-core/src/dbgpt/model/utils/parse_utils.py
  packages/dbgpt-core/src/dbgpt/model/utils/tests/test_parse_utils.py
  packages/dbgpt-core/src/dbgpt/rag/embedding/embeddings.py
  packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_clickhouse.py
  pyproject.toml
  uv.lock
Labels: fix, model

#2397 refactor(dbgpts): Refactor dbgpts for 0.7.0
  packages/dbgpt-app/pyproject.toml
  packages/dbgpt-core/src/dbgpt/cli/cli_scripts.py
  packages/dbgpt-core/src/dbgpt/configs/model_config.py
  packages/dbgpt-core/src/dbgpt/core/interface/llm.py
  packages/dbgpt-core/src/dbgpt/model/llm/llama_cpp/llama_cpp.py
  packages/dbgpt-core/src/dbgpt/model/llm/llama_cpp/llama_cpp_server.py
  packages/dbgpt-core/src/dbgpt/model/llm/llm_out/hf_chat_llm.py
  packages/dbgpt-core/src/dbgpt/model/llm/llm_out/vllm_llm.py
  packages/dbgpt-core/src/dbgpt/rag/embedding/embeddings.py
  packages/dbgpt-core/src/dbgpt/util/dbgpts/cli.py
  packages/dbgpt-core/src/dbgpt/util/dbgpts/repo.py
  packages/dbgpt-core/src/dbgpt/util/dbgpts/template.py
  packages/dbgpt-core/src/dbgpt/util/system_utils.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/service/share_utils.py
  uv.lock
Labels: internal

#2405 fix(model): Fix reasoning output bug
  packages/dbgpt-app/src/dbgpt_app/initialization/serve_initialization.py
  packages/dbgpt-core/src/dbgpt/core/interface/llm.py
Labels: fix, model

#2413 fix(code): Fix build lyric error
  packages/dbgpt-core/pyproject.toml
  uv.lock
Labels: fix

#2420 feat(agents): add ReActAgent
  examples/agents/react_agent_example.py
  packages/dbgpt-core/src/dbgpt/agent/expand/actions/react_action.py
  packages/dbgpt-core/src/dbgpt/agent/expand/react_agent.py
Labels: enhancement, agent

#2421 chore: fix unit test
  docs/docs/installation/integrations/graph_rag_install.md
  packages/dbgpt-core/src/dbgpt/agent/resource/tool/tests/test_base_tool.py
  packages/dbgpt-core/src/dbgpt/core/awel/flow/tests/test_flow_variables.py
  packages/dbgpt-core/src/dbgpt/core/interface/tests/test_prompt.py
  packages/dbgpt-core/src/dbgpt/model/cluster/apiserver/tests/test_api.py
  packages/dbgpt-core/src/dbgpt/util/prompt_util.py
  packages/dbgpt-core/src/dbgpt/util/tests/configure/test_manager.py
  packages/dbgpt-core/src/dbgpt/util/tests/test_module_utils.py
  packages/dbgpt-core/src/dbgpt/util/tests/test_parameter_utils.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/summary/tests/test_rdbms_summary.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/tests/test_db_struct_assembler.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/community/memgraph_store_adapter.py
  packages/dbgpt-serve/src/dbgpt_serve/agent/chat/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/agent/chat/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/conversation/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/conversation/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/core/tests/conftest.py
  packages/dbgpt-serve/src/dbgpt_serve/dbgpts/hub/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/dbgpts/hub/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/dbgpts/my/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/dbgpts/my/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/feedback/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/feedback/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/file/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/file/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/libro/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/libro/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/model/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/model/tests/test_models.py
  packages/dbgpt-serve/src/dbgpt_serve/model/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/prompt/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/prompt/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/tests/test_service.py
  packages/dbgpt-serve/src/dbgpt_serve/utils/_template_files/default_serve_template/tests/test_endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/utils/_template_files/default_serve_template/tests/test_service.py
Labels: internal

#2419 docs: add ollama docs
  docs/docs/quickstart.md
Labels: documentation

#2310 fix(agent): move app resource implement to serv pkg
  packages/dbgpt-app/src/dbgpt_app/component_configs.py
  packages/dbgpt-core/src/dbgpt/agent/resource/app.py
  packages/dbgpt-serve/src/dbgpt_serve/agent/resource/app.py
Labels: fix, agent

#2443 fix(chat): Fix chat completions API error
  packages/dbgpt-app/src/dbgpt_app/scene/base_chat.py
Labels: fix

#2441 fix: aembed_query type error
  packages/dbgpt-core/src/dbgpt/model/cluster/embedding/remote_embedding.py
Labels: fix

#2446 fix(docker): Fix build arm image bug
  .github/workflows/docker-image-publish-openai.yml
  .github/workflows/docker-image-publish.yml
  docker/base/Dockerfile
Labels: fix

#2456 fix(datasource): Correct the import path for StarRocks dialect
  packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/dialect/starrocks/sqlalchemy/__init__.py
  packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/dialect/starrocks/sqlalchemy/dialect.py
Labels: fix

#2457 feat(dbgpt-serve): Agent fixes and parameter additions
  packages/dbgpt-core/src/dbgpt/core/interface/message.py
  packages/dbgpt-serve/src/dbgpt_serve/agent/db/gpts_app.py
  packages/dbgpt-serve/src/dbgpt_serve/agent/db/gpts_conversations_db.py
  packages/dbgpt-serve/src/dbgpt_serve/agent/db/gpts_messages_db.py
Labels: enhancement

#2461 fix(awel): Fix AWEL flow error
  packages/dbgpt-app/src/dbgpt_app/operators/rag.py
  packages/dbgpt-core/src/dbgpt/core/awel/flow/base.py
  packages/dbgpt-core/src/dbgpt/core/awel/flow/compat.py
  packages/dbgpt-core/src/dbgpt/core/awel/flow/flow_factory.py
  packages/dbgpt-core/src/dbgpt/util/cli/flow_compat.py
  packages/dbgpt-core/src/dbgpt/vis/tags/vis_chart.py
  packages/dbgpt-core/src/dbgpt/vis/tags/vis_dashboard.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/compat/0.7.0_compat_flow.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/service/service.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/embedded-knowledge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/hybrid-knowledge-process-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/kg-knowledge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/rag-chat-awel-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/embedded-knowledge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/hybrid-knowldge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/kg-knowledge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/rag-chat-awel-flow-template.json
Labels: fix

#2465 fix (vector store) Database refresh error, vector collection deduplication consistency issue
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py
Labels: fix

#2464 fix(chat-excel):Explicitly create data tables from the `df` (#2437)
  packages/dbgpt-app/src/dbgpt_app/scene/chat_data/chat_excel/excel_learning/prompt.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_data/chat_excel/excel_reader.py
Labels: fix

#2472 fix(knowledge recall test): Add system_app parameter to knowledgeSpaceRetriever initialization
  packages/dbgpt-app/src/dbgpt_app/knowledge/service.py
Labels: fix

#2434 refactor: rag storage refactor
  configs/dbgpt-bm25-rag.toml
  docs/docs/installation/integrations/bm25_rag_install.md
  docs/sidebars.js
  examples/rag/bm25_retriever_example.py
  examples/rag/cross_encoder_rerank_example.py
  examples/rag/db_schema_rag_example.py
  examples/rag/embedding_rag_example.py
  examples/rag/graph_rag_example.py
  examples/rag/keyword_rag_example.py
  examples/rag/metadata_filter_example.py
  examples/rag/rag_embedding_api_example.py
  examples/rag/retriever_evaluation_example.py
  examples/rag/simple_dbschema_retriever_example.py
  examples/rag/simple_rag_embedding_example.py
  examples/rag/simple_rag_retriever_example.py
  packages/dbgpt-app/src/dbgpt_app/component_configs.py
  packages/dbgpt-app/src/dbgpt_app/config.py
  packages/dbgpt-app/src/dbgpt_app/dbgpt_server.py
  packages/dbgpt-app/src/dbgpt_app/knowledge/api.py
  packages/dbgpt-app/src/dbgpt_app/knowledge/service.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_knowledge/v1/chat.py
  packages/dbgpt-core/src/dbgpt/component.py
  packages/dbgpt-core/src/dbgpt/storage/base.py
  packages/dbgpt-core/src/dbgpt/storage/graph_store/base.py
  packages/dbgpt-core/src/dbgpt/storage/knowledge_graph/base.py
  packages/dbgpt-core/src/dbgpt/storage/vector_store/base.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/assembler/bm25.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/assembler/db_schema.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/retriever/graph_retriever/graph_retriever.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/transformer/graph_extractor.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/__init__.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/full_text/elasticsearch.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/graph_store/tugraph_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/community/community_metastore.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/community/community_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/community_summary.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/knowledge_graph.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/elastic_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/factory.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/oceanbase_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/pgvector_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/weaviate_store.py
  packages/dbgpt-serve/src/dbgpt_serve/datasource/service/db_summary_client.py
  packages/dbgpt-serve/src/dbgpt_serve/datasource/service/service.py
  packages/dbgpt-serve/src/dbgpt_serve/evaluate/service/service.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/connector.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/operators/knowledge_space.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/retriever/knowledge_space.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/service/service.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/storage_manager.py
Labels: fix, internal

#2480 fix(LLM extractor): handle empty response in LLM extractor
  packages/dbgpt-app/src/dbgpt_app/knowledge/service.py
  packages/dbgpt-core/src/dbgpt/rag/transformer/llm_extractor.py
Labels: fix

#2485 fix:issue2484
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py
Labels: fix

#2466 chore(build):add vscode devcontainer config
  .devcontainer.json
  .devcontainer/Dockerfile.dev
  .devcontainer/dbgpt.pth
  .devcontainer/init_env.sh
  .devcontainer/post-create.sh
  Makefile
  pyproject.toml
Labels: internal

#2490 fix:doris_conn cannot get table comment to store vectordb
  packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_doris.py
Labels: fix

#2500 fix(core): Fix param cache error
  packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/api_v1.py
  packages/dbgpt-core/src/dbgpt/util/configure/manager.py
  packages/dbgpt-core/src/dbgpt/util/configure/markdown.py
  packages/dbgpt-core/src/dbgpt/util/parameter_utils.py
Labels: fix, core

#2481 fix: milvus collection search param
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py
Labels: fix

#2509 fix: rag knowledge process workflow template
  packages/dbgpt-core/src/dbgpt/storage/knowledge_graph/base.py
  packages/dbgpt-core/src/dbgpt/storage/vector_store/base.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/operators/knowledge_graph.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/operators/process_branch.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/operators/vector_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/graph_store/tugraph_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/community_summary.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/knowledge_graph.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/elastic_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/oceanbase_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/pgvector_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/weaviate_store.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/embedded-knowledge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/hybrid-knowledge-process-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/kg-knowledge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/embedded-knowledge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/hybrid-knowldge-process-flow-template.json
  packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/kg-knowledge-process-flow-template.json
Labels: fix

#2510 fix(log): Modify AWEL init log param
  packages/dbgpt-core/src/dbgpt/core/awel/__init__.py
Labels: fix

#2513 chore(style): Code format
  packages/dbgpt-core/src/dbgpt/core/awel/__init__.py
Labels: internal

#2515 docs: Add 0.7.0 release blog
  README.ja.md
  README.md
  docs/blog/2025-03-24-dbgpt-v0.7.0-release.md
  docs/static/img/v070/Knowledge_thinking.png
  docs/static/img/v070/chat_excel.png
  docs/static/img/v070/chat_latex.png
  docs/static/img/v070/contributors.png
  docs/static/img/v070/data_analysis.png
  docs/static/img/v070/datasource.png
  docs/static/img/v070/graphrag_1.png
  docs/static/img/v070/graphrag_2.png
  docs/static/img/v070/mcp_chat_app.png
  docs/static/img/v070/mcp_config_app.png
  docs/static/img/v070/mcp_create_app.png
  docs/static/img/v070/model_deploy.png
  docs/static/img/v070/simple_awel.png
Labels: documentation

#2517 docs: Fix build doc error
  docs/Dockerfile-deploy
Labels: documentation

#2532 fix: wrong name close #2530
  packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/editor/_chat_history/meta_db_history.py
  packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/editor/api_editor_v1.py
Labels: fix

#2533 fix: clouse issue #2469 by fixing the type
  packages/dbgpt-app/src/dbgpt_app/scene/chat_db/professional_qa/chat.py
Labels: fix

#2544 feat(KnowledgeBase):Add Word97-2003 (.doc) Binary File parsing module
  .devcontainer.json
  .devcontainer/Dockerfile.dev
  .devcontainer/README.md
  .devcontainer/init_env.sh
  .devcontainer/post-create.sh
  .gitignore
  CONTRIBUTING.md
  docker/base/Dockerfile
  packages/dbgpt-core/src/dbgpt/rag/knowledge/base.py
  packages/dbgpt-ext/pyproject.toml
  packages/dbgpt-ext/src/dbgpt_ext/rag/knowledge/__init__.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/knowledge/doc.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/knowledge/factory.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/knowledge/tests/data/test_mock.doc
  packages/dbgpt-ext/src/dbgpt_ext/rag/knowledge/tests/test_doc.py
  uv.lock
Labels: enhancement

#2550 fix: issue 2549
  packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/api_v1.py
Labels: fix

#2552 fix: some typos using typos
  docker/base/Dockerfile
  docs/docs/application/advanced_tutorial/api.md
  docs/docs/application/fine_tuning_manual/text_to_sql.md
  docs/docs/faq/kbqa.md
  packages/dbgpt-app/src/dbgpt_app/knowledge/_cli/knowledge_client.py
Labels: fix

#2555 fix: fix vllm tokenizer count error
  packages/dbgpt-core/src/dbgpt/model/cluster/worker/default_worker.py
Labels: fix

#2551 fix: make tugraph work again
  packages/dbgpt-ext/src/dbgpt_ext/datasource/conn_tugraph.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/summary/gdbms_db_summary.py
Labels: fix

#2565 fix(knowledge):Fix KB document questions list check logic
  packages/dbgpt-serve/src/dbgpt_serve/rag/service/service.py
Labels: fix
