Repository eosphoros-ai/DB-GPT, pull requests merged in 2025-06, with the labels that each got.

#2754 feat(model): Support MiniCPM4-8B
  README.ja.md
  README.md
  README.zh.md
  packages/dbgpt-core/src/dbgpt/model/adapter/hf_adapter.py
  packages/dbgpt-core/src/dbgpt/model/adapter/model_metadata.py
  packages/dbgpt-core/src/dbgpt/model/proxy/llms/siliconflow.py
  packages/dbgpt-core/src/dbgpt/model/proxy/llms/tongyi.py
Labels: enhancement, model

#2760 docs: update readme
  README.ja.md
  README.md
  README.zh.md
  assets/LOGO_SMALL.png
  assets/Twitter_LOGO.png
  assets/Youtube_LOGO.png
Labels: documentation

#2771 chore: tag v0.7.2
  packages/dbgpt-app/src/dbgpt_app/_version.py
  packages/dbgpt-client/src/dbgpt_client/_version.py
  packages/dbgpt-core/src/dbgpt/_version.py
  packages/dbgpt-ext/src/dbgpt_ext/_version.py
  packages/dbgpt-serve/src/dbgpt_serve/_version.py
  pyproject.toml
Labels: internal

#2772 feat(model): Support Qwen3 embeddings
  configs/dbgpt-local-qwen3.example.toml
  configs/dbgpt-proxy-infiniai.toml
  configs/dbgpt-proxy-siliconflow-mysql.toml
  configs/dbgpt-proxy-siliconflow.toml
  packages/dbgpt-core/src/dbgpt/model/adapter/embed_metadata.py
  packages/dbgpt-core/src/dbgpt/rag/embedding/embeddings.py
  packages/dbgpt-core/src/dbgpt/rag/embedding/rerank.py
  tests/intetration_tests/datasource/test_conn_starrocks.py
Labels: enhancement, model

#2783 fix(model): Fix proxy reranker bug
  packages/dbgpt-core/src/dbgpt/rag/embedding/rerank.py
Labels: fix, model

#2794 feat(AWEL):Add operator for structured output data of datasource in AWEL
  packages/dbgpt-app/src/dbgpt_app/operators/datasource.py
  packages/dbgpt-serve/src/dbgpt_serve/flow/compat/0.7.0_compat_flow.json
Labels: enhancement

#2798 chore: update create chroma store param
  docs/docs/agents/modules/memory/hybrid_memory.md
  docs/docs/agents/modules/memory/long_term_memory.md
  docs/docs/awel/cookbook/first_rag_with_awel.md
  docs/docs/awel/cookbook/write_your_chat_database.md
  examples/awel/simple_nl_schema_sql_chart_example.py
  examples/sdk/chat_data_with_awel.py
  packages/dbgpt-core/src/dbgpt/agent/core/memory/hybrid.py
Labels: internal

#2802 feat(core): Support export messages
  packages/dbgpt-core/src/dbgpt/vis/tags/vis_thinking.py
  packages/dbgpt-serve/src/dbgpt_serve/conversation/api/endpoints.py
  packages/dbgpt-serve/src/dbgpt_serve/conversation/api/schemas.py
  packages/dbgpt-serve/src/dbgpt_serve/conversation/models/models.py
Labels: enhancement, core
