Repository eosphoros-ai/DB-GPT, pull requests merged in 2025-01, with the labels that each got.

#2263 feat(model): Support llama.cpp server deploy
  dbgpt/core/schema/api.py
  dbgpt/model/adapter/base.py
  dbgpt/model/adapter/llama_cpp_adapter.py
  dbgpt/model/adapter/loader.py
  dbgpt/model/adapter/model_adapter.py
  dbgpt/model/base.py
  dbgpt/model/cluster/apiserver/api.py
  dbgpt/model/cluster/base.py
  dbgpt/model/cluster/worker/default_worker.py
  dbgpt/model/cluster/worker/remote_worker.py
  dbgpt/model/llm/llama_cpp/llama_cpp.py
  docs/docs/installation/advanced_usage/Llamacpp_server.md
  docs/sidebars.js
  setup.py
Labels: enhancement, model

#2270 chore:wechat update
  assets/wechat.jpg
  docs/sidebars.js
Labels: internal

#2267 fix(security): fix path traversal vulnerability (CVE-2024-10834)
  dbgpt/serve/agent/hub/plugin_hub.py
Labels: fix

#2265 feat(agent): add app starter role in mutli agent
  dbgpt/agent/resource/app.py
  dbgpt/agent/resource/base.py
  dbgpt/app/component_configs.py
  dbgpt/serve/agent/agents/app_agent_manage.py
  dbgpt/serve/agent/agents/expand/__init__.py
  dbgpt/serve/agent/agents/expand/app_resource_start_assisant_agent.py
Labels: enhancement, agent

#2271 fix(docs): Fix document build error
  .github/workflows/doc-image-publish.yml
  docs/Dockerfile-deploy
  docs/patchs/fix_0.6.3.patch
Labels: fix

#2273 fix(ci): Fix push document image error
  .github/workflows/doc-image-publish.yml
  .github/workflows/pylint.yml
  .github/workflows/test-python.yml
Labels: fix

#2275 fix(agent): format problem
  dbgpt/agent/resource/app.py
  dbgpt/app/component_configs.py
  dbgpt/serve/agent/agents/app_agent_manage.py
  dbgpt/serve/agent/agents/expand/__init__.py
  dbgpt/serve/agent/agents/expand/app_resource_start_assisant_agent.py
Labels: fix, agent

#2268 fix(security): prevent arbitrary file write in SQL editor (CVE-2024-10835)
  dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
Labels: fix

#2269 fix(security): prevent SQL injection in chart data query (CVE-2024-10901)
  dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
Labels: fix

#2279 fix(ci): Fix build docker image error
  .github/workflows/doc-image-publish.yml
  .github/workflows/docker-image-publish.yml
Labels: fix

#2278 fix(app):remove invaild file
  dbgpt/app/img.png
Labels: fix

#2290 fix(agent): Fix load db models error
  dbgpt/agent/resource/app.py
  dbgpt/serve/agent/agents/controller.py
Labels: fix, agent

#2289 fix(json_utils): fix function find_json_objects
  dbgpt/util/json_utils.py
  dbgpt/util/tests/test_json_utils.py
Labels: fix

#2309 feature(agent): Knowledge add retriever name&desc getter and stter
  dbgpt/agent/resource/knowledge.py
  dbgpt/serve/agent/resource/knowledge.py
Labels: enhancement
