Repository eosphoros-ai/DB-GPT, pull requests merged in 2025-02, with the labels that each got.

#2325 fix:issue2323
  dbgpt/app/scene/base_chat.py
  dbgpt/client/schema.py
  dbgpt/serve/datasource/api/schemas.py
Labels: fix

#2298 fix(agent): agent's llmclient bug
  dbgpt/agent/util/llm/llm_client.py
Labels: fix, agent

#2361 refactor:adapt rag storage and add integration documents.
  configs/dbgpt-graphrag.toml
  docs/docs/api/app.md
  docs/docs/api/chat.md
  docs/docs/api/datasource.md
  docs/docs/api/knowledge.md
  docs/docs/cookbook/rag/graph_rag_app_develop.md
  docs/docs/installation/graph_rag_install.md
  docs/docs/installation/integrations.md
  docs/docs/installation/milvus_rag_install.md
  docs/sidebars.js
  examples/client/client_chat_example.py
  packages/dbgpt-app/src/dbgpt_app/config.py
  packages/dbgpt-app/src/dbgpt_app/knowledge/service.py
  packages/dbgpt-app/src/dbgpt_app/openapi/api_v2.py
  packages/dbgpt-app/src/dbgpt_app/scene/chat_knowledge/v1/chat.py
  packages/dbgpt-core/src/dbgpt/storage/base.py
  packages/dbgpt-core/src/dbgpt/storage/vector_store/base.py
  packages/dbgpt-ext/pyproject.toml
  packages/dbgpt-ext/src/dbgpt_ext/storage/__init__.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/graph_store/factory.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/graph_store/tugraph_store.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/knowledge_graph/knowledge_graph.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/__init__.py
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py
  packages/dbgpt-serve/src/dbgpt_serve/core/service.py
  packages/dbgpt-serve/src/dbgpt_serve/datasource/service/db_summary_client.py
  packages/dbgpt-serve/src/dbgpt_serve/rag/connector.py
Labels: internal

#2368 fix(i18n): Fix read i18n config error
  packages/dbgpt-core/src/dbgpt/util/i18n_utils.py
Labels: fix

#2371 fix(model): Fix local embedding error
  .dockerignore
  configs/dbgpt-local-llama-cpp-server.toml
  configs/dbgpt-local-qwen.toml
  configs/dbgpt-proxy-deepseek.toml
  packages/dbgpt-accelerator/pyproject.toml
  packages/dbgpt-core/src/dbgpt/rag/embedding/embeddings.py
  uv.lock
Labels: fix, model
