Repository eosphoros-ai/DB-GPT, pull requests merged in 2025-07, with the labels that each got.

#2810 feat:add storage client cache
  packages/dbgpt-serve/src/dbgpt_serve/rag/storage_manager.py
Labels: enhancement

#2847 fix(core): Update Milvus truncate method for GraphRAG
  packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py
Labels: fix, core

#2844 feat(model): AI/ML API integration
  configs/dbgpt-proxy-aimlapi.toml
  docker/base/Dockerfile
  docs/docs/config-reference/llm/aimlapi_aimlapideploymodelparameters_a1b2c3.mdx
  docs/docs/config-reference/llm/index.mdx
  docs/docs/installation/docker.md
  docs/docs/installation/docker_compose.md
  docs/docs/installation/integrations/aimlapi_llm_install.md
  packages/dbgpt-core/src/dbgpt/model/proxy/__init__.py
  packages/dbgpt-core/src/dbgpt/model/proxy/llms/aimlapi.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/embeddings/__init__.py
  packages/dbgpt-ext/src/dbgpt_ext/rag/embeddings/aimlapi.py
Labels: enhancement, model

#2855 docs: update CONTRIBUTING.md to use uv package manager
  CONTRIBUTING.md
Labels: documentation

#2812 feat(agent): Add count field and support non-ASCII characters in DataScientist action output
  packages/dbgpt-core/src/dbgpt/agent/expand/actions/chart_action.py
Labels: enhancement, agent

#2862 fix(awel): Fix HO context key error
  packages/dbgpt-app/src/dbgpt_app/operators/datasource.py
  packages/dbgpt-app/src/dbgpt_app/operators/rag.py
Labels: fix
